-- Piloto de la migracion (Etapa 2): tablas personas + iva, RLS sobre personas.
-- Correr conectado a la base 'carnisys' con el rol carnisys_admin (dueno de las tablas,
-- para que RLS no lo bypasee por ownership -- ver docs/06-datos-e-integraciones/rls-postgres.md).

CREATE TABLE iva (
    id integer PRIMARY KEY,
    iva text NOT NULL,
    abrev text
);

CREATE TABLE personas (
    -- GENERATED BY DEFAULT (no ALWAYS): permite insertar los IDs reales tal cual durante
    -- la migracion de datos (algunos son hardcodeados en el codigo, ej. Consumidor Final=6),
    -- y de ahi en mas se autoincrementa solo para las altas nuevas.
    idpersona integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identificacion text,
    razonsocial text,
    -- Sin REFERENCES iva(id): SQL Server tampoco tiene esa FK real (confirmado en
    -- docs/08-relevamiento/snapshot-2026-08-18/schema-fks.txt) y hay filas reales con
    -- idiva=0 (sentinela "sin IVA"), fiel al esquema de origen.
    idiva integer,
    cuit text,
    telefono text,
    email text,
    domicilio text,
    ciudad text,
    otrosdatos text,
    tipo text,
    ctacte boolean NOT NULL DEFAULT false,
    bonificacion real NOT NULL DEFAULT 0,
    marca boolean NOT NULL DEFAULT false,
    idpropietario integer REFERENCES personas(idpersona),
    idempresa integer NOT NULL DEFAULT 0,
    -- Nullable: hay filas reales en SQL Server con creado=NULL (datos legacy), fiel al origen.
    creado timestamptz DEFAULT now()
);

CREATE INDEX ix_personas_idempresa ON personas(idempresa);

ALTER TABLE personas ENABLE ROW LEVEL SECURITY;

CREATE POLICY personas_rls ON personas
    FOR ALL
    USING (
        current_setting('app.id_empresa', true) IS NOT NULL
        AND current_setting('app.id_empresa', true) <> ''
        AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0)
    )
    WITH CHECK (
        idempresa = current_setting('app.id_empresa', true)::int
    );

GRANT SELECT, INSERT, UPDATE, DELETE ON personas, iva TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE personas_idpersona_seq TO carnisys_user, cs_admin_pg;

-- Despues de este script: migrar los datos reales de Iva y Personas desde SQL Server
-- (export via sqlcmd con EsAdminCarniSys=1 para ver todos los tenants, conversion a UTF-8,
-- carga via "\copy" conectado como carnisys_admin para preservar los IDs exactos -- ver
-- docs/DECISIONS.md, entrada 2026-08-18, para el detalle completo del proceso). Los datos
-- en si NO se versionan en el repo (son datos reales, aunque sean de una base de desarrollo).
-- Despues de cargar los datos con IDs explicitos, resetear la secuencia:
--   SELECT setval('personas_idpersona_seq', (SELECT MAX(idpersona) FROM personas));
