-- Modulo Empleados y Liquidacion de Sueldos (2026-09-29, ver docs/DECISIONS.md). Modulo 100% nuevo,
-- solo Postgres -- no hay tabla equivalente en SQL Server para portar.
--
-- Ficha de empleado: 1:1 con personas (datos personales + cuenta corriente donde se acredita el
-- sueldo) y 1:1 con usuarios (login propio para marcar su jornada) -- ux_empleado_idpersona y
-- ux_empleado_idusuario garantizan el 1:1 a nivel de base. Sin FOREIGN KEY explicito hacia
-- personas/usuarios, mismo criterio ya usado en cortepuntostocksucursal/dispositivosseguros (esta
-- base no usa FKs declarativos, la integridad la garantiza la capa de aplicacion).
--
-- legajo: codigo interno de busqueda/filtro, distinto del CUIT/DNI (que ya vive en
-- personas.identificacion) -- unico por empresa.
--
-- Correr conectado a 'carnisys' con el rol carnisys_admin.
CREATE TABLE empleado (
    idempleado integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempresa integer NOT NULL,
    idpersona integer NOT NULL,
    idusuario integer NOT NULL,
    legajo text NOT NULL,
    formaliquidacion text NOT NULL,
    fechaingreso timestamp NOT NULL DEFAULT now(),
    fechabaja timestamp,
    activo boolean NOT NULL DEFAULT true,
    creado timestamp NOT NULL DEFAULT now(),
    creadopor integer,
    actualizado timestamp,
    actualizadopor integer
);

CREATE UNIQUE INDEX ux_empleado_idpersona ON empleado(idpersona);
CREATE UNIQUE INDEX ux_empleado_idusuario ON empleado(idusuario);
CREATE UNIQUE INDEX ux_empleado_empresa_legajo ON empleado(idempresa, legajo);
CREATE INDEX ix_empleado_empresa_activo ON empleado(idempresa, activo);

ALTER TABLE empleado ENABLE ROW LEVEL SECURITY;

CREATE POLICY empleado_rls ON empleado FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT, UPDATE, DELETE ON empleado TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE empleado_idempleado_seq TO carnisys_user, cs_admin_pg;
