-- Etapa 5: MovCtaCte, Pagos, Cheques, Bancos (con RLS) + Usuarios (tabla de apoyo, sin RLS,
-- mismo criterio que Iva/Empresas). Correr conectado a 'carnisys' con el rol carnisys_admin.
-- Sin FKs explicitas: SQL Server tampoco las tiene en estas 4 tablas (confirmado en
-- schema-fks.txt), fidelidad al esquema real.

CREATE TABLE usuarios (
    id integer PRIMARY KEY,
    nombre text,
    usuario text,
    email text,
    idsucursaluser integer,
    idempresa integer NOT NULL DEFAULT 0
);

CREATE TABLE bancos (
    banco text,
    pais text,
    idempresa integer NOT NULL DEFAULT 0
);

CREATE TABLE movctacte (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idpersona integer,
    fecha timestamp,
    tabla text,
    idtabla integer,
    detalle text,
    tipo text,
    importe double precision,
    idsucursal integer,
    creado timestamp,
    creadopor integer,
    actualizado timestamp,
    actualizadopor integer,
    quitadoctacte boolean NOT NULL DEFAULT false,
    nrodoc text,
    idempresa integer NOT NULL DEFAULT 0
);

CREATE TABLE pagos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nrorecibo text,
    fecha timestamp,
    idpersona integer,
    aproveedor boolean NOT NULL DEFAULT false,
    formapago text,
    banco text,
    nrocheque text,
    titularcheque text,
    importe double precision,
    observaciones text,
    idsucursal integer,
    creado timestamp,
    creadopor integer,
    actualizado timestamp,
    actualizadopor integer,
    efectivo double precision NOT NULL DEFAULT 0,
    idempresa integer NOT NULL DEFAULT 0
);

-- Cheques.id es identity en SQL Server pero SIN constraint de PK declarada (confirmado en
-- schema-columnas.txt, es_pk=0) -- se replica igual, identity sin PK.
CREATE TABLE cheques (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    nrocheque text,
    banco text,
    propio boolean NOT NULL DEFAULT false,
    fechaemision text,
    fechapago date,
    importe double precision,
    estado text,
    titular text,
    observaciones text,
    recibidode integer,
    entregadoa integer,
    creado timestamp,
    creadopor integer,
    actualizado timestamp,
    actualizadopor integer,
    idempresa integer NOT NULL DEFAULT 0
);

CREATE INDEX ix_movctacte_idempresa ON movctacte(idempresa);
CREATE INDEX ix_pagos_idempresa ON pagos(idempresa);
CREATE INDEX ix_cheques_idempresa ON cheques(idempresa);
CREATE INDEX ix_bancos_idempresa ON bancos(idempresa);

ALTER TABLE movctacte ENABLE ROW LEVEL SECURITY;
ALTER TABLE pagos ENABLE ROW LEVEL SECURITY;
ALTER TABLE cheques ENABLE ROW LEVEL SECURITY;
ALTER TABLE bancos ENABLE ROW LEVEL SECURITY;

CREATE POLICY movctacte_rls ON movctacte FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

CREATE POLICY pagos_rls ON pagos FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

CREATE POLICY cheques_rls ON cheques FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

CREATE POLICY bancos_rls ON bancos FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT, UPDATE, DELETE ON movctacte, pagos, cheques, bancos, usuarios TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE movctacte_id_seq, pagos_id_seq, cheques_id_seq TO carnisys_user, cs_admin_pg;
