-- Etapa 10: cambiarSucursalCaja/obtenerPreviewCambioSucursalCaja necesitan mover filas de
-- Expendios (idsucursal), tabla que nunca se habia portado (queda pendiente el resto de
-- Venta.cs: CRUD completo, Sectores, FacturaElectronica). Se trae el schema y los datos reales
-- completos aca (94 filas, activamente usada por PuntosExpendioController/POS -- no es una
-- tabla obsoleta), aunque esta etapa solo implementa las 2 consultas que necesita
-- cambiarSucursalCaja (select de ids por filtro + update idsucursal). Ver docs/DECISIONS.md,
-- Etapa 10.
-- Verificado contra la base CarniSys real antes de escribir esto (columnas, identity, RLS).
-- Correr conectado a 'carnisys' con el rol carnisys_admin.

CREATE TABLE expendios (
    idexpendio integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idvendedor integer,
    fechaexpendio timestamp,
    identificacionexpendio text,
    sector text,
    idsucursal integer,
    creado timestamp,
    cantitems integer,
    importe double precision,
    idventa integer,
    idempresa integer NOT NULL DEFAULT 0,
    observaciones text
);

CREATE INDEX ix_expendios_idempresa ON expendios(idempresa);

ALTER TABLE expendios ENABLE ROW LEVEL SECURITY;

CREATE POLICY expendios_rls ON expendios FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT, UPDATE, DELETE ON expendios TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE expendios_idexpendio_seq TO carnisys_user, cs_admin_pg;

-- AuditoriaCambioSucursalCaja: en SQL Server el original NO tiene RLS (se crea de forma
-- perezosa via DDL idempotente en Datos/CierreCaja.cs, sin CREATE POLICY) -- se preserva la
-- misma fidelidad aca, no es un olvido. En Postgres se provisiona de entrada (no en tiempo de
-- ejecucion) para no tener que emitir DDL desde CierreCajaPg.
CREATE TABLE auditoriacambiosucursalcaja (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempresa integer NOT NULL,
    idcierrecaja integer NOT NULL,
    idusuarioejecutor integer NOT NULL,
    usuarioejecutor text,
    idusuariocaja integer NOT NULL,
    usuariocaja text,
    idsucursalanterior integer NOT NULL,
    sucursalanterior text,
    idsucursalnueva integer NOT NULL,
    sucursalnueva text,
    fechadesde timestamp NOT NULL,
    fechahasta timestamp NOT NULL,
    fechacambio timestamp NOT NULL,
    detalle text
);

GRANT SELECT, INSERT ON auditoriacambiosucursalcaja TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE auditoriacambiosucursalcaja_id_seq TO carnisys_user, cs_admin_pg;
