-- Login por huella digital / passkeys WebAuthn (2026-09-21, ver docs/DECISIONS.md "Login por
-- huella (passkeys)"). Una fila por huella/passkey registrada por un usuario. Solo guarda la
-- CLAVE PUBLICA y el contador de uso: la huella en si nunca sale del dispositivo del usuario.
-- Solo Postgres (SQL Server legado no tiene esta funcionalidad).
-- Correr como carnisys_admin (dueno de las tablas), ANTES de desplegar el codigo.

CREATE TABLE usuariopasskeys (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idusuario       integer NOT NULL,
    idempresa       integer NOT NULL,
    credentialid    bytea   NOT NULL,
    publickey       bytea   NOT NULL,
    signcount       bigint  NOT NULL DEFAULT 0,
    userhandle      bytea   NOT NULL,
    aaguid          uuid,
    transports      text,
    nombre          text    NOT NULL,
    -- timestamptz (no "timestamp"): Npgsql 8 mapea DateTime Kind=Utc a timestamptz y rechaza/
    -- desplaza el valor contra "timestamp without time zone".
    fechaaltautc    timestamp with time zone NOT NULL DEFAULT now(),
    ultimousoutc    timestamp with time zone
);

-- Un credentialId identifica una passkey en todo el sistema: el login lo busca sin conocer el
-- tenant todavia.
CREATE UNIQUE INDEX ux_usuariopasskeys_credentialid ON usuariopasskeys (credentialid);
CREATE INDEX ix_usuariopasskeys_usuario ON usuariopasskeys (idempresa, idusuario);

-- RLS por empresa, mismo patron que usuarios / usuariopasswordresettokens
-- (20260821-Alter_usuarios_usuariopasswordresettokens_RLS_UniqueUsuario.sql).
ALTER TABLE usuariopasskeys ENABLE ROW LEVEL SECURITY;

CREATE POLICY usuariopasskeys_rls ON usuariopasskeys
    USING (
        current_setting('app.id_empresa', true) IS NOT NULL
        AND current_setting('app.id_empresa', true) <> ''
        AND idempresa = current_setting('app.id_empresa', true)::integer
    )
    WITH CHECK (
        idempresa = current_setting('app.id_empresa', true)::integer
    );

GRANT SELECT, INSERT, UPDATE, DELETE ON usuariopasskeys TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE usuariopasskeys_id_seq TO carnisys_user, cs_admin_pg;

-- El login por huella busca la credencial por credentialid SIN saber la empresa (el tenant sale
-- de la propia fila): usa el rol bypass ya existente, igual que la busqueda de usuarios
-- (DatosPostgres/UsuarioPg.cs AbrirSinRLS).
GRANT SELECT, UPDATE ON usuariopasskeys TO carnisys_usuarios_bypass;
