-- Etapa 12c: bloque FacturaElectronica de Venta.cs (ultimo de Venta.cs, que queda 47/47
-- migrado). Verificado contra la base CarniSys real antes de escribir esto (columnas,
-- identity, RLS). Correr conectado a 'carnisys' con el rol carnisys_admin.
--
-- error es tinyint en SQL Server (no bit) -- se mapea a boolean igual que pesoBalanza en la
-- Etapa 12b. alicuotasiva NO tiene idEmpresa en el original -- tabla de referencia global
-- (alicuotas de IVA), compartida entre todas las empresas -- sin RLS, mismo criterio que otras
-- tablas de catalogo global del proyecto.

CREATE TABLE facturaelectronica (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ptovtaafip text,
    fechaemisionafip timestamp,
    desctipocbteafip text,
    codtipocbteafip integer,
    nrocbteafip text,
    tipodocafip text,
    nrodocafip text,
    razonsocialafip text,
    condicionivaafip text,
    domicilioafip text,
    condicionventa text,
    formapago text,
    cae text,
    fecvtocae text,
    importenetogravado double precision,
    iva double precision,
    importetotal double precision,
    idventa integer,
    creado timestamp,
    error boolean,
    mensajeerror text,
    fechaerror timestamp,
    canterrores integer NOT NULL DEFAULT 0,
    porcentajefacturacion double precision,
    descitemunitario text,
    idempresa integer NOT NULL DEFAULT 0,
    observaciones text NOT NULL DEFAULT ''
);

CREATE INDEX ix_facturaelectronica_idempresa ON facturaelectronica(idempresa);
CREATE INDEX ix_facturaelectronica_idventa ON facturaelectronica(idventa);

ALTER TABLE facturaelectronica ENABLE ROW LEVEL SECURITY;

CREATE POLICY facturaelectronica_rls ON facturaelectronica FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT, UPDATE, DELETE ON facturaelectronica TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE facturaelectronica_id_seq TO carnisys_user, cs_admin_pg;

CREATE TABLE alicuotaivaporfactura (
    idalicuotaivafactura integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idfacturaelectronica integer NOT NULL,
    idiva integer NOT NULL,
    baseimponible double precision,
    importe double precision,
    idempresa integer NOT NULL DEFAULT 0
);

CREATE INDEX ix_alicuotaivaporfactura_idempresa ON alicuotaivaporfactura(idempresa);
CREATE INDEX ix_alicuotaivaporfactura_idfacturaelectronica ON alicuotaivaporfactura(idfacturaelectronica);

ALTER TABLE alicuotaivaporfactura ENABLE ROW LEVEL SECURITY;

CREATE POLICY alicuotaivaporfactura_rls ON alicuotaivaporfactura FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT, UPDATE, DELETE ON alicuotaivaporfactura TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE alicuotaivaporfactura_idalicuotaivafactura_seq TO carnisys_user, cs_admin_pg;

-- alicuotasiva YA EXISTIA (migrada en la Etapa 6, junto con el bloque CRUD/referencia de
-- Corte.cs -- obtenerAlicuotasIva/findAlicuotaIvaById en ICorteRepository.cs comparten esta
-- misma tabla fisica con getAlicuotaIvaFactura de Venta.cs). Verificado con \d + SELECT antes
-- de escribir este script: mismo schema (idiva/iva/orden/mostrar, sin idempresa, sin RLS) y
-- las mismas 6 filas reales ya presentes -- no hace falta CREATE TABLE ni migracion de datos
-- aca, se deja esta nota en vez del CREATE para que el script no rompa si se reintenta.
