-- Etapa 9: Compra.cs completo -- compras, corteporcompra, mediares, corteproveedor (nueva,
-- encontrada al leer agregarCortePorCompra). Verificado contra la base CarniSys real antes de
-- escribir esto (columnas, RLS, identity) -- ver docs/DECISIONS.md, Etapa 9.
-- Sin FKs explicitas: SQL Server tampoco las tiene.
-- Correr conectado a 'carnisys' con el rol carnisys_admin.

CREATE TABLE compras (
    idcompra integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado text,
    fechacompra timestamp,
    nroremito text,
    idproveedor integer,
    tipocompra text,
    observaciones text,
    idsucursal integer,
    creado timestamp,
    creadopor integer,
    actualizado timestamp,
    actualizadopor integer,
    cantmedias integer,
    enctacte boolean,
    kgsmedias integer,
    idpesajeajustado integer,
    idempresa integer NOT NULL DEFAULT 0
);

CREATE TABLE corteporcompra (
    idcorteporcompra integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idcompra integer,
    idcorte integer,
    idsucursal integer,
    preciokg double precision,
    cantkg double precision,
    creado timestamp,
    creadopor integer,
    balanza boolean,
    idempresa integer NOT NULL DEFAULT 0
);

CREATE TABLE mediares (
    idmedia integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idcompra integer,
    kgmedia double precision,
    preciomedia double precision,
    nrotropa text,
    idsucursal integer,
    idempresa integer NOT NULL DEFAULT 0
);

CREATE TABLE corteproveedor (
    idcorteproveedor integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idcorte integer NOT NULL,
    idproveedor integer NOT NULL,
    ultimoprecio double precision,
    fechaultimacompra timestamp,
    idempresa integer NOT NULL DEFAULT 0
);

CREATE INDEX ix_compras_idempresa ON compras(idempresa);
CREATE INDEX ix_corteporcompra_idempresa ON corteporcompra(idempresa);
CREATE INDEX ix_mediares_idempresa ON mediares(idempresa);
CREATE INDEX ix_corteproveedor_idempresa ON corteproveedor(idempresa);
CREATE INDEX ix_corteporcompra_idcompra ON corteporcompra(idcompra);
CREATE INDEX ix_mediares_idcompra ON mediares(idcompra);
CREATE INDEX ix_corteproveedor_proveedor_corte ON corteproveedor(idproveedor, idcorte);

ALTER TABLE compras ENABLE ROW LEVEL SECURITY;
ALTER TABLE corteporcompra ENABLE ROW LEVEL SECURITY;
ALTER TABLE mediares ENABLE ROW LEVEL SECURITY;
ALTER TABLE corteproveedor ENABLE ROW LEVEL SECURITY;

CREATE POLICY compras_rls ON compras FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

CREATE POLICY corteporcompra_rls ON corteporcompra FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

CREATE POLICY mediares_rls ON mediares FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

CREATE POLICY corteproveedor_rls ON corteproveedor FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT, UPDATE, DELETE ON compras, corteporcompra, mediares, corteproveedor TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE compras_idcompra_seq, corteporcompra_idcorteporcompra_seq, mediares_idmedia_seq, corteproveedor_idcorteproveedor_seq TO carnisys_user, cs_admin_pg;
