-- Borradores en servidor de Compras, Stock, Movimientos y Embutidos (alta/edicion), con eventos y
-- notificaciones al admin -- mismo espiritu que ventaborrador (ver 20260921b-...sql y
-- docs/DECISIONS.md "Ventas en curso: borrador en servidor y advertencias del POS"), pero generico:
-- una sola tabla reusada por los 4 modulos (columna "modulo"), en vez de una copia de ventaborrador
-- por cada uno. Solo Postgres: con DataEngine=SqlServer la funcion queda apagada (esas pantallas
-- siguen con el borrador local en localStorage y el respaldo por captura de pantalla de siempre).
-- Correr como carnisys_admin (dueno de las tablas), ANTES de desplegar el codigo.
--
-- Por que separada de ventaborrador (no se migra Ventas aca): VentaBorrador tiene acoplamientos
-- propios de POS que no aplican aca (idventa/FinalizarVenta, cierre de caja, logout de POS) -- forzarlos
-- en una tabla compartida dejaria columnas siempre NULL para estos 4 modulos o iria al reves. Ver
-- docs/DECISIONS.md "Borradores de Compras/Stock/Movimientos/Embutidos".

-- ---------------------------------------------------------------------------------------------
-- 1) Borrador generico: una fila por formulario en curso (compra, movimiento de stock, traslado,
--    o carga de embutido), se actualiza en el lugar mientras el operador lo arma. "Interrumpido" NO
--    es un estado guardado: es ACTIVA con ultimolatido mas viejo que el umbral (igual que ventaborrador).
-- ---------------------------------------------------------------------------------------------
CREATE TABLE borradorgenerico (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempresa        integer NOT NULL,
    idsucursal       integer NOT NULL,
    modulo           varchar(30) NOT NULL,             -- COMPRA / STOCK / MOVIMIENTO / EMBUTIDO_CARGA / EMBUTIDO_RAPIDO
    idregistro       integer,                          -- id del registro que se esta editando (NULL = alta nueva)
    idoperador       integer NOT NULL,                 -- operador real (resuelto por cada modulo)
    idusuariosesion  integer NOT NULL,                 -- cuenta con la que se inicio sesion (puede ser la compartida)
    clientid         uuid    NOT NULL,                 -- token del formulario generado por el navegador
    resumen          text,                              -- 1 linea armada por el modulo (proveedor/sucursales/producto), sin parsear el payload
    cantlineas       integer NOT NULL DEFAULT 0,
    payload          jsonb,                             -- forma especifica de cada modulo, opaca para Negocio
    estado           varchar(12) NOT NULL DEFAULT 'ACTIVA',
    idresultado      integer,                           -- id de lo creado al confirmar (idcompra/idmovimiento/idembutido)
    creado           timestamp NOT NULL DEFAULT now(),
    ultimolatido     timestamp NOT NULL DEFAULT now(),
    actualizado      timestamp,
    finalizado       timestamp,
    CONSTRAINT ck_borradorgenerico_modulo CHECK (modulo IN ('COMPRA', 'STOCK', 'MOVIMIENTO', 'EMBUTIDO_CARGA', 'EMBUTIDO_RAPIDO')),
    CONSTRAINT ck_borradorgenerico_estado CHECK (estado IN ('ACTIVA', 'FINALIZADA', 'DESCARTADA'))
);

CREATE UNIQUE INDEX ux_borradorgenerico_empresa_clientid ON borradorgenerico (idempresa, clientid);
CREATE INDEX ix_borradorgenerico_sucursal_modulo_estado ON borradorgenerico (idempresa, idsucursal, modulo, estado, ultimolatido);
CREATE INDEX ix_borradorgenerico_operador_modulo_estado ON borradorgenerico (idempresa, idoperador, modulo, estado);

ALTER TABLE borradorgenerico ENABLE ROW LEVEL SECURITY;

CREATE POLICY borradorgenerico_rls ON borradorgenerico FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND idempresa = current_setting('app.id_empresa', true)::int)
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT, UPDATE, DELETE ON borradorgenerico TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE borradorgenerico_id_seq TO carnisys_user, cs_admin_pg;

-- ---------------------------------------------------------------------------------------------
-- 2) Eventos de un borrador generico (append-only): cierre de pestana, logout, recuperado, descartado.
--    Solo INSERT/SELECT: lo registrado no se puede alterar ni borrar. Sin CIERRE_CAJA: estos 4
--    modulos no tienen caja.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE borradorgenericoevento (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempresa     integer NOT NULL,
    idborrador    integer NOT NULL,
    fecha         timestamp NOT NULL DEFAULT now(),
    tipo          varchar(20) NOT NULL,
    idusuario     integer NOT NULL,                    -- quien hizo la accion
    detalle       text,
    CONSTRAINT ck_borradorgenericoevento_tipo CHECK (tipo IN ('CIERRE_PESTANA', 'LOGOUT', 'RECUPERADA', 'DESCARTADA'))
);

CREATE INDEX ix_borradorgenericoevento_borrador ON borradorgenericoevento (idempresa, idborrador, fecha);
CREATE INDEX ix_borradorgenericoevento_fecha ON borradorgenericoevento (idempresa, fecha);

ALTER TABLE borradorgenericoevento ENABLE ROW LEVEL SECURITY;

CREATE POLICY borradorgenericoevento_rls ON borradorgenericoevento FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND idempresa = current_setting('app.id_empresa', true)::int)
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT ON borradorgenericoevento TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE borradorgenericoevento_id_seq TO carnisys_user, cs_admin_pg;

-- ---------------------------------------------------------------------------------------------
-- 3) notificaciones: sin migracion (tipo ya es varchar(30) sin CHECK, ver 20260921b-...sql). Los tipos
--    nuevos (BORRADOR_DESCARTADO_COMPRA / _STOCK / _MOVIMIENTO / _EMBUTIDO_CARGA / _EMBUTIDO_RAPIDO)
--    se agregan solo a nivel de aplicacion, en Entidades.Notificacion.
-- ---------------------------------------------------------------------------------------------
