-- Tabla override para poder marcar un corte como "independiente" (y decidir si aparece en
-- el cierre de stock) en una sucursal puntual, sin cambiar su configuracion global. Mismo
-- diseno que Datos/DB-Procedures/20260917-Create_CorteJerarquiaSucursal.sql (SQL Server), ya
-- probado contra la base local supercerdo antes de aplicar esto (ver docs/DECISIONS.md,
-- 2026-09-17). Correr conectado a 'carnisys' con el rol carnisys_admin.
--
-- Deliberadamente sin idcortemaestro: el override solo puede marcar "independiente"/"en
-- cierre de stock", nunca redirigir a un corte maestro distinto por sucursal.
CREATE TABLE cortejerarquiasucursal (
    idcortejerarquiasucursal integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempresa integer NOT NULL,
    idcorte integer NOT NULL,
    idsucursal integer NOT NULL,
    independiente boolean NOT NULL,
    encierrestock boolean NOT NULL,
    creado timestamp NOT NULL DEFAULT now(),
    actualizado timestamp
);

CREATE UNIQUE INDEX ux_cortejerarquiasucursal_empresa_corte_sucursal ON cortejerarquiasucursal(idempresa, idcorte, idsucursal);
CREATE INDEX ix_cortejerarquiasucursal_corte_sucursal ON cortejerarquiasucursal(idcorte, idsucursal);

ALTER TABLE cortejerarquiasucursal ENABLE ROW LEVEL SECURITY;

CREATE POLICY cortejerarquiasucursal_rls ON cortejerarquiasucursal FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT, UPDATE, DELETE ON cortejerarquiasucursal TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE cortejerarquiasucursal_idcortejerarquiasucursal_seq TO carnisys_user, cs_admin_pg;
