-- Etapa 13a: bloque CRUD/login core de Usuario.cs. "usuarios" ya existia como stub minimo
-- (creado para los lookups de GetUsuarioLiviano en CortePg/VentaPg, 6 columnas, 15 filas
-- reales, SIN RLS) -- se ALTERa, no se recrea.
--
-- DECISION IMPORTANTE, confirmada con el usuario: "usuarios" NO lleva RLS, a diferencia de
-- toda otra tabla multi-tenant de esta migracion. En el momento del login todavia no se sabe
-- a que empresa pertenece el usuario -- si hubiera RLS filtrando por app.id_empresa, la propia
-- consulta de login no podria encontrar la fila porque ese contexto no existe todavia.
-- Verificado contra la base real: la tabla Usuarios de SQL Server TAMPOCO tiene RLS
-- (sys.security_policies/sys.security_predicates, 0 filas). El aislamiento por tenant se
-- resuelve a nivel de aplicacion (WHERE idempresa=@idEmpresa explicito en las queries que
-- corresponda), igual que ya hace Datos/Usuario.cs.
--
-- "id" pasa a ser IDENTITY (decision del usuario, no se replica el patron MAX(id)+1 con
-- UPDLOCK/HOLDLOCK del SP original -- que el propio equipo original ya habia marcado como
-- riesgoso: "OJO: MAX+1 puede colisionar con concurrencia; ideal seria IDENTITY o SEQUENCE").
-- Mismo patron IDENTITY que toda otra tabla nueva de esta migracion.
--
-- admin/activo son tinyint en SQL Server (no bit) -- se mapean a boolean, mismo criterio que
-- pesoBalanza/error en etapas anteriores.
--
-- Verificado contra la base CarniSys real antes de escribir esto (columnas, tipos). Correr
-- conectado a 'carnisys' con el rol carnisys_admin.

ALTER TABLE usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE usuarios
    ADD COLUMN clave text NOT NULL DEFAULT '',
    ADD COLUMN admin boolean NOT NULL DEFAULT false,
    ADD COLUMN activo boolean NOT NULL DEFAULT true,
    ADD COLUMN colorform text,
    ADD COLUMN passwordhash text,
    ADD COLUMN passwordsalt text,
    ADD COLUMN passwordhashiterations integer,
    ADD COLUMN passwordupdatedatutc timestamp,
    ADD COLUMN permitirloginfuerasucursal boolean NOT NULL DEFAULT false,
    ADD COLUMN superadmin boolean NOT NULL DEFAULT false,
    ADD COLUMN esusuarioproduccion boolean NOT NULL DEFAULT false,
    ADD COLUMN intentosfallidoslogin integer NOT NULL DEFAULT 0,
    ADD COLUMN bloqueado boolean NOT NULL DEFAULT false,
    ADD COLUMN fechabloqueoutc timestamp;

-- Formularios: catalogo global de pantallas del sistema, sin idempresa -- sin RLS, mismo
-- criterio que alicuotasiva (catalogo compartido entre todas las empresas).
CREATE TABLE formularios (
    idform integer PRIMARY KEY,
    nombreform text,
    descripcion text,
    formconsulta text,
    formedicion text,
    formedicionextra1 text,
    formedicionextra2 text
);

GRANT SELECT ON formularios TO carnisys_user, cs_admin_pg;

-- PermisosUsuarios: permisos por usuario y formulario, tiene idempresa -- RLS estandar. Se
-- crea en esta sub-etapa porque addOrEditUser (alta de usuario) inserta permisos por defecto
-- aca (ver Negocio/Usuario.cs -- dependencia cruzada encontrada durante el scoping); los
-- metodos propios de lectura/edicion de permisos (getPermisosUsuario/AddOrEditPermisos) son
-- la Etapa 13b.
CREATE TABLE permisosusuarios (
    idusuario integer NOT NULL,
    idform integer NOT NULL,
    diaspermitidosver integer NOT NULL DEFAULT -1,
    diaspermitidoseditar integer NOT NULL DEFAULT -1,
    soloregistrospropios boolean NOT NULL DEFAULT true,
    idempresa integer NOT NULL DEFAULT 0,
    PRIMARY KEY (idusuario, idform)
);

CREATE INDEX ix_permisosusuarios_idempresa ON permisosusuarios(idempresa);

ALTER TABLE permisosusuarios ENABLE ROW LEVEL SECURITY;

CREATE POLICY permisosusuarios_rls ON permisosusuarios FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT, UPDATE, DELETE ON permisosusuarios TO carnisys_user, cs_admin_pg;
