-- Fase 1 de la integracion con Mercado Pago Point (plan de sesion 2026-08-31, ver
-- docs/DECISIONS.md). No existe en el modelo ningun concepto previo de "caja/terminal fisica"
-- persistente (Sucursal es lo unico estable; CierreCaja es transaccional; posInstanceId es
-- efimero por pestana de navegador) -- esta tabla nace de cero para eso. Una Sucursal puede
-- tener 1 o mas terminales Point.
CREATE TABLE terminales_mercadopago (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempresa integer NOT NULL,
    idsucursal integer NOT NULL,
    terminalidmp text NOT NULL,
    alias text,
    activo boolean NOT NULL DEFAULT true,
    fechaaltautc timestamp NOT NULL
);

CREATE INDEX ix_terminales_mercadopago_idempresa ON terminales_mercadopago(idempresa);
CREATE INDEX ix_terminales_mercadopago_idsucursal ON terminales_mercadopago(idsucursal);

ALTER TABLE terminales_mercadopago ENABLE ROW LEVEL SECURITY;

CREATE POLICY terminales_mercadopago_rls ON terminales_mercadopago FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT, UPDATE, DELETE ON terminales_mercadopago TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE terminales_mercadopago_id_seq TO carnisys_user, cs_admin_pg;
