-- Modulo Empleados y Liquidacion de Sueldos (2026-09-29, ver docs/DECISIONS.md).
--
-- Una corrida de liquidacion de sueldo para un empleado y un periodo. Solo el devengamiento del
-- sueldo bruto -- se acredita en la cuenta corriente de la Persona del empleado via
-- movctacte(tabla='Liquidaciones', tipo='Credito'). periododesde/periodohasta son timestamp (no
-- solo date): el usuario elige fecha+hora, necesario para cortar con precision el tiempo trabajado
-- de los empleados por Hora.
--
-- No se permite superponer periodos Confirmada del mismo empleado -- validado en
-- Negocio.LiquidacionSueldo (aplicacion), no hay EXCLUDE constraint (mismo criterio de esta base:
-- sin constraints declarativos complejos, la regla vive en la capa de negocio).
--
-- Correr conectado a 'carnisys' con el rol carnisys_admin.
CREATE TABLE liquidacionsueldo (
    idliquidacionsueldo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempresa integer NOT NULL,
    idempleado integer NOT NULL,
    periododesde timestamp NOT NULL,
    periodohasta timestamp NOT NULL,
    fechaliquidacion date NOT NULL DEFAULT now(),
    totalliquidado numeric(14,2) NOT NULL,
    detallectacte text,
    estado text NOT NULL DEFAULT 'Confirmada',
    creado timestamp NOT NULL DEFAULT now(),
    creadopor integer
);

CREATE INDEX ix_liquidacionsueldo_empleado ON liquidacionsueldo(idempleado, periododesde, periodohasta);
CREATE INDEX ix_liquidacionsueldo_empleado_estado ON liquidacionsueldo(idempleado, estado);

ALTER TABLE liquidacionsueldo ENABLE ROW LEVEL SECURITY;

CREATE POLICY liquidacionsueldo_rls ON liquidacionsueldo FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT, UPDATE, DELETE ON liquidacionsueldo TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE liquidacionsueldo_idliquidacionsueldo_seq TO carnisys_user, cs_admin_pg;
