-- Modulo Empleados y Liquidacion de Sueldos (2026-09-29, ver docs/DECISIONS.md).
--
-- Desglose de una liquidacionsueldo (transparencia/auditoria). origen='Automatico' = calculado por
-- el sistema a partir de registrojornada, dias de vacaciones o el fijo del periodo; 'Manual' =
-- agregado por el usuario en el preview (Premio, Bono, Aguinaldo, ajuste). sintarifaconfigurada=true
-- cuando el sistema no encontro una empleadotarifa para esa combinacion turno/dia: valorunitario
-- queda en 0 y la linea se muestra resaltada para que el usuario la complete antes de aprobar
-- (nunca se inventa un valor -- ver CLAUDE.md §2.7).
--
-- idempresa denormalizado desde liquidacionsueldo (mismo criterio de RLS por defense-in-depth ya
-- usado en el resto de la base) -- sin FOREIGN KEY explicito hacia liquidacionsueldo, mismo
-- criterio que el resto de esta base (sin constraints declarativos, integridad a nivel app).
--
-- Correr conectado a 'carnisys' con el rol carnisys_admin.
CREATE TABLE liquidacionsueldodetalle (
    idliquidacionsueldodetalle integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempresa integer NOT NULL DEFAULT 0,
    idliquidacionsueldo integer NOT NULL,
    concepto text NOT NULL,
    origen text NOT NULL DEFAULT 'Automatico',
    cantidad numeric(10,2) NOT NULL,
    valorunitario numeric(14,2) NOT NULL,
    subtotal numeric(14,2) NOT NULL,
    sintarifaconfigurada boolean NOT NULL DEFAULT false
);

CREATE INDEX ix_liquidacionsueldodetalle_liquidacion ON liquidacionsueldodetalle(idliquidacionsueldo);

ALTER TABLE liquidacionsueldodetalle ENABLE ROW LEVEL SECURITY;

CREATE POLICY liquidacionsueldodetalle_rls ON liquidacionsueldodetalle FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0);

GRANT SELECT, INSERT, UPDATE, DELETE ON liquidacionsueldodetalle TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE liquidacionsueldodetalle_idliquidacionsueldodetalle_seq TO carnisys_user, cs_admin_pg;
