-- Ventas en curso (borrador en servidor), productos pesados sin agregar y notificaciones al admin
-- (2026-09-21, ver docs/DECISIONS.md "Ventas en curso: borrador en servidor y advertencias del POS").
-- Solo Postgres (mismo criterio que usuariopasskeys): con DataEngine=SqlServer la funcion queda apagada.
-- Correr como carnisys_admin (dueno de las tablas), ANTES de desplegar el codigo.
--
-- REGLA DE DISENO: el borrador de una venta NUNCA se escribe en ventas/lineaventa. Varias consultas de
-- totales, cierre de caja, stock y reportes no filtran ventas.estado ni excluyen lineas "en curso":
-- una fila borrador ahi contaminaria todo. Las lineas viven solo en el payload jsonb de ventaborrador.

-- ---------------------------------------------------------------------------------------------
-- 1) Venta en curso: una fila por carrito, se actualiza en el lugar mientras el cajero arma la venta.
--    "Interrumpida" NO es un estado guardado: es ACTIVA con ultimolatido mas viejo que el umbral.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE ventaborrador (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempresa        integer NOT NULL,
    idsucursal       integer NOT NULL,
    idoperador       integer NOT NULL,              -- operador real (ResolverOperadorPOS)
    idusuariosesion  integer NOT NULL,              -- cuenta con la que se inicio sesion (puede ser la compartida)
    clientid         uuid    NOT NULL,              -- token del carrito generado por el navegador
    posinstanceid    text,
    idcierrecaja     integer,
    idpersona        integer,
    razonsocial      text,
    cantlineas       integer NOT NULL DEFAULT 0,
    total            numeric(14,2) NOT NULL DEFAULT 0,
    payload          jsonb,                         -- lineas/expendios/forma de pago/cliente/observaciones (forma de POSDraft)
    estado           varchar(12) NOT NULL DEFAULT 'ACTIVA',
    idventa          integer,
    creado           timestamp NOT NULL DEFAULT now(),
    ultimolatido     timestamp NOT NULL DEFAULT now(),
    actualizado      timestamp,
    finalizado       timestamp,
    CONSTRAINT ck_ventaborrador_estado CHECK (estado IN ('ACTIVA', 'FINALIZADA', 'DESCARTADA'))
);

CREATE UNIQUE INDEX ux_ventaborrador_empresa_clientid ON ventaborrador (idempresa, clientid);
CREATE INDEX ix_ventaborrador_sucursal_estado ON ventaborrador (idempresa, idsucursal, estado, ultimolatido);
CREATE INDEX ix_ventaborrador_operador_estado ON ventaborrador (idempresa, idoperador, estado);

ALTER TABLE ventaborrador ENABLE ROW LEVEL SECURITY;

CREATE POLICY ventaborrador_rls ON ventaborrador FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND idempresa = current_setting('app.id_empresa', true)::int)
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT, UPDATE, DELETE ON ventaborrador TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE ventaborrador_id_seq TO carnisys_user, cs_admin_pg;

-- ---------------------------------------------------------------------------------------------
-- 2) Eventos de una venta en curso (append-only): cierre de pestana, logout, cierre de caja,
--    recuperada, descartada. Solo INSERT/SELECT: lo registrado no se puede alterar ni borrar.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE ventaborradorevento (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempresa     integer NOT NULL,
    idborrador    integer NOT NULL,
    fecha         timestamp NOT NULL DEFAULT now(),
    tipo          varchar(20) NOT NULL,
    idusuario     integer NOT NULL,                 -- quien hizo la accion
    detalle       text,
    CONSTRAINT ck_ventaborradorevento_tipo CHECK (tipo IN ('CIERRE_PESTANA', 'LOGOUT', 'CIERRE_CAJA', 'RECUPERADA', 'DESCARTADA'))
);

CREATE INDEX ix_ventaborradorevento_borrador ON ventaborradorevento (idempresa, idborrador, fecha);
CREATE INDEX ix_ventaborradorevento_fecha ON ventaborradorevento (idempresa, fecha);

ALTER TABLE ventaborradorevento ENABLE ROW LEVEL SECURITY;

CREATE POLICY ventaborradorevento_rls ON ventaborradorevento FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND idempresa = current_setting('app.id_empresa', true)::int)
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT ON ventaborradorevento TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE ventaborradorevento_id_seq TO carnisys_user, cs_admin_pg;

-- ---------------------------------------------------------------------------------------------
-- 3) Producto pesado que quedo en pantalla con cantidad estable > umbral y salio SIN agregarse al
--    carrito (fraude "pesar, cobrar y borrar el codigo"). Nunca se borra. inicio/fin los calcula el
--    servidor (no el reloj del navegador). Unico dato modificable: la revision del admin (UPDATE
--    solo sobre esas 4 columnas).
-- ---------------------------------------------------------------------------------------------
CREATE TABLE ventaproductosinagregar (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempresa           integer NOT NULL,
    idsucursal          integer NOT NULL,
    idoperador          integer NOT NULL,
    idusuariosesion     integer NOT NULL,
    clientid            uuid,                        -- carrito activo en ese momento (enlaza con ventaborrador)
    codigo              text NOT NULL,
    producto            text NOT NULL,
    preciokg            numeric(14,2) NOT NULL,
    cantidadkg          numeric(14,3) NOT NULL,
    importe             numeric(14,2) NOT NULL,
    segundosenpantalla  integer NOT NULL,
    segundosestables    integer NOT NULL,
    origen              varchar(10) NOT NULL,
    motivo              varchar(20) NOT NULL,
    inicio              timestamp NOT NULL,          -- cuando se tipeo / aparecio el producto
    fin                 timestamp NOT NULL,          -- cuando se borro / salio
    creado              timestamp NOT NULL DEFAULT now(),
    revision            varchar(12),                 -- NULL = sin revisar
    revisadapor         integer,
    revisadaen          timestamp,
    comentariorevision  text,
    CONSTRAINT ck_ventaproductosinagregar_origen CHECK (origen IN ('BALANZA', 'MANUAL')),
    CONSTRAINT ck_ventaproductosinagregar_motivo CHECK (motivo IN ('CODIGO_BORRADO', 'CODIGO_CAMBIADO', 'CANTIDAD_CERO', 'FINALIZAR', 'CIERRE_PESTANA')),
    CONSTRAINT ck_ventaproductosinagregar_revision CHECK (revision IS NULL OR revision IN ('JUSTIFICADA', 'SOSPECHOSA'))
);

CREATE INDEX ix_ventaproductosinagregar_fin ON ventaproductosinagregar (idempresa, fin);
CREATE INDEX ix_ventaproductosinagregar_operador_fin ON ventaproductosinagregar (idempresa, idoperador, fin);

ALTER TABLE ventaproductosinagregar ENABLE ROW LEVEL SECURITY;

CREATE POLICY ventaproductosinagregar_rls ON ventaproductosinagregar FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND idempresa = current_setting('app.id_empresa', true)::int)
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT ON ventaproductosinagregar TO carnisys_user, cs_admin_pg;
-- Permiso de UPDATE a nivel columna: solo se puede agregar la revision del admin.
GRANT UPDATE (revision, revisadapor, revisadaen, comentariorevision) ON ventaproductosinagregar TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE ventaproductosinagregar_id_seq TO carnisys_user, cs_admin_pg;

-- ---------------------------------------------------------------------------------------------
-- 4) Notificaciones al admin (campana del topbar). "Atendida" es compartido entre admins: queda
--    quien la reviso. UNIQUE(idempresa, tipo, refid) para crearlas de forma idempotente; para
--    PRODUCTO_SIN_AGREGAR el refid es la clave operador+dia (una sola notificacion por cajero y dia,
--    que se actualiza y se reabre con cada evento nuevo).
-- ---------------------------------------------------------------------------------------------
CREATE TABLE notificaciones (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempresa     integer NOT NULL,
    idsucursal    integer,
    tipo          varchar(30) NOT NULL,
    severidad     varchar(12) NOT NULL DEFAULT 'ADVERTENCIA',
    titulo        text NOT NULL,
    mensaje       text NOT NULL,
    refid         bigint NOT NULL,
    creado        timestamp NOT NULL DEFAULT now(),
    actualizado   timestamp,
    atendidapor   integer,
    atendidaen    timestamp,
    CONSTRAINT ck_notificaciones_severidad CHECK (severidad IN ('ADVERTENCIA', 'INFO'))
);

CREATE UNIQUE INDEX ux_notificaciones_empresa_tipo_refid ON notificaciones (idempresa, tipo, refid);
CREATE INDEX ix_notificaciones_pendientes ON notificaciones (idempresa, atendidaen, actualizado);

ALTER TABLE notificaciones ENABLE ROW LEVEL SECURITY;

CREATE POLICY notificaciones_rls ON notificaciones FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND idempresa = current_setting('app.id_empresa', true)::int)
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT, UPDATE ON notificaciones TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE notificaciones_id_seq TO carnisys_user, cs_admin_pg;
