-- Etapa 8: bloque CierreCaja/EgresosCaja/TiposEgresoCaja de CierreCaja.cs. Verificado contra
-- la base CarniSys real antes de escribir esto (columnas, RLS, identity) -- ver
-- docs/DECISIONS.md, Etapa 8. Sin FKs explicitas: SQL Server tampoco las tiene.
-- Correr conectado a 'carnisys' con el rol carnisys_admin.
--
-- cierrecaja.id: en SQL Server NO es identity (esquema propio namespaced por sucursal, ver
-- DECISIONS.md). En Postgres, decision del usuario, id ES autoincremental
-- (GENERATED BY DEFAULT AS IDENTITY) -- divergencia deliberada, solo del lado Postgres.
-- tiposegresocaja.id: tampoco es identity en el origen (el C# genera MAX(id)+1 a mano) --
-- se replica ese mismo esquema en Postgres (columna id normal, sin IDENTITY).

CREATE TABLE cierrecaja (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idsucursal integer,
    fechahorainicio timestamp,
    fechahoracierre timestamp,
    cajainicio double precision,
    ventas double precision,
    gastos double precision,
    saldocaja double precision,
    cajacierre double precision,
    diferencia double precision,
    cajainiciosiguiente double precision,
    importeretirado double precision,
    usuarioinicio text,
    usuariocierre text,
    creado timestamp,
    actualizado timestamp,
    idempresa integer NOT NULL DEFAULT 0
);

CREATE TABLE tiposegresocaja (
    id integer PRIMARY KEY,
    tipoegresocaja text,
    orden integer,
    escompra boolean,
    esgasto boolean,
    reservadosistema boolean,
    creado timestamp,
    actualizado timestamp,
    idempresa integer NOT NULL DEFAULT 0
);

CREATE TABLE egresoscaja (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fechahora timestamp,
    idtipoegresocaja integer,
    descripcion text,
    detalle text,
    monto double precision,
    idsucursal integer,
    creado timestamp,
    creadopor integer,
    actualizado timestamp,
    actualizadopor integer,
    idcompra integer,
    esgasto boolean,
    tabla text,
    idtabla integer,
    idempresa integer NOT NULL DEFAULT 0
);

CREATE INDEX ix_cierrecaja_idempresa ON cierrecaja(idempresa);
CREATE INDEX ix_tiposegresocaja_idempresa ON tiposegresocaja(idempresa);
CREATE INDEX ix_egresoscaja_idempresa ON egresoscaja(idempresa);
CREATE INDEX ix_egresoscaja_tabla_idtabla ON egresoscaja(tabla, idtabla);

ALTER TABLE cierrecaja ENABLE ROW LEVEL SECURITY;
ALTER TABLE tiposegresocaja ENABLE ROW LEVEL SECURITY;
ALTER TABLE egresoscaja ENABLE ROW LEVEL SECURITY;

CREATE POLICY cierrecaja_rls ON cierrecaja FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

CREATE POLICY tiposegresocaja_rls ON tiposegresocaja FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

CREATE POLICY egresoscaja_rls ON egresoscaja FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT, UPDATE, DELETE ON cierrecaja, tiposegresocaja, egresoscaja TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE cierrecaja_id_seq, egresoscaja_id_seq TO carnisys_user, cs_admin_pg;
