-- Solicitud de autorizacion de dispositivo al administrador (2026-10-02, ver docs/DECISIONS.md
-- "Login por CUIT, clave rapida (PIN) y politica de clave", Fase 1c). Espeja
-- Datos/DB-Procedures/20261002b-Create_DispositivosSeguros_Solicitudes.sql (SQL Server).
--
-- Un usuario que puso bien su clave desde un dispositivo no autorizado (en una empresa que exige
-- dispositivo seguro) puede pedirle al administrador que lo autorice, sin copiar ni mandar el codigo
-- del dispositivo. El admin ve las solicitudes pendientes en /DispositivosSeguros y las aprueba
-- (se agrega a dispositivosseguros) o rechaza. Correr como carnisys_admin (dueno de las tablas).
--
-- RLS estandar por idempresa, igual que dispositivosseguros.
CREATE TABLE IF NOT EXISTS dispositivosseguros_solicitudes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempresa integer NOT NULL,
    idusuario integer NOT NULL,
    -- Mismo "numero de serie" que se guardaria en dispositivosseguros ("web:" + SHA-256 de la cookie
    -- del navegador, o el ID de hardware del agente de impresion).
    serie text NOT NULL,
    nombre text NOT NULL,
    mensaje text,
    ip text,
    estado text NOT NULL DEFAULT 'pendiente',
    creadautc timestamp NOT NULL,
    resueltapor integer,
    resueltautc timestamp,
    CONSTRAINT ck_dispositivosseguros_solicitudes_estado CHECK (estado IN ('pendiente', 'aprobada', 'rechazada'))
);

CREATE INDEX IF NOT EXISTS ix_dispsolicitudes_idempresa_estado ON dispositivosseguros_solicitudes(idempresa, estado);
CREATE INDEX IF NOT EXISTS ix_dispsolicitudes_serie ON dispositivosseguros_solicitudes(serie);

ALTER TABLE dispositivosseguros_solicitudes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS dispositivosseguros_solicitudes_rls ON dispositivosseguros_solicitudes;
CREATE POLICY dispositivosseguros_solicitudes_rls ON dispositivosseguros_solicitudes FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT, UPDATE, DELETE ON dispositivosseguros_solicitudes TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE dispositivosseguros_solicitudes_id_seq TO carnisys_user, cs_admin_pg;
