-- Etapa: DispositivoSeguro.cs (cuarto de los modulos chicos 0%-migrados). 4 metodos: Listar,
-- Agregar, Eliminar, ExisteSerieSegura (usado en el login, antes de autenticar, para saltear
-- LoginRateLimiter -- el idEmpresa ya se conoce en ese punto, resuelto del candidato por
-- usuario/email, no hay problema de tenant-todavia-no-conocido como en usuarios).
--
-- Tabla vacia en SQL Server (0 filas reales) -- no hace falta migracion de datos.
--
-- idempresa: mismo patron ya encontrado 2 veces en esta ronda de modulos chicos
-- (empresaparametros, cortepuntostocksucursal) -- SQL Server no tiene RLS aca tampoco
-- (verificado, 0 filas en sys.security_policies). Se agrega RLS estandar en Postgres como
-- mejora deliberada, mismo criterio ya confirmado con el usuario para los casos anteriores.
CREATE TABLE dispositivosseguros (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempresa integer NOT NULL,
    numeroserie text NOT NULL,
    descripcion text,
    creadoutc timestamp NOT NULL,
    idusuariocreador integer
);

CREATE INDEX ix_dispositivosseguros_idempresa ON dispositivosseguros(idempresa);
CREATE INDEX ix_dispositivosseguros_numeroserie ON dispositivosseguros(numeroserie);

ALTER TABLE dispositivosseguros ENABLE ROW LEVEL SECURITY;

CREATE POLICY dispositivosseguros_rls ON dispositivosseguros FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT, UPDATE, DELETE ON dispositivosseguros TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE dispositivosseguros_id_seq TO carnisys_user, cs_admin_pg;
