-- Etapa 11b: Corte.cs, bloque Movimiento -- movimiento, cortepormovimiento, movimientohistorial.
-- Verificado contra la base CarniSys real antes de escribir esto (columnas, identity, RLS).
-- Sin FKs explicitas: SQL Server tampoco las tiene.
-- Correr conectado a 'carnisys' con el rol carnisys_admin.

CREATE TABLE movimiento (
    idmovimiento integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fechamovimiento timestamp,
    sucursalorigen integer,
    sucursaldestino integer,
    observaciones text,
    creado timestamp,
    actualizado timestamp,
    idmovorigen integer,
    actualizacioncompleta smallint,
    creadopor integer,
    actualizadopor integer,
    idempresa integer NOT NULL DEFAULT 0
);

CREATE TABLE cortepormovimiento (
    idcortemovimiento integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idmovimientos integer,
    idcorte integer,
    cantkg double precision,
    pesobalanza boolean,
    cantunidad integer,
    permitiringreso smallint,
    idempresa integer NOT NULL DEFAULT 0
);

-- Sin PK ni identity en el original (tabla de auditoria insert-only, se replica igual).
CREATE TABLE movimientohistorial (
    idmovimiento integer,
    fechamovimiento timestamp,
    idsucorigen integer,
    idsucdestino integer,
    idcorte integer,
    cantkg double precision,
    cantunidad integer,
    pesobalanza boolean,
    actualizadopor integer,
    actualizado timestamp,
    observaciones text,
    idempresa integer NOT NULL DEFAULT 0
);

CREATE INDEX ix_movimiento_idempresa ON movimiento(idempresa);
CREATE INDEX ix_cortepormovimiento_idempresa ON cortepormovimiento(idempresa);
CREATE INDEX ix_cortepormovimiento_idmovimientos ON cortepormovimiento(idmovimientos);
CREATE INDEX ix_movimientohistorial_idempresa ON movimientohistorial(idempresa);
CREATE INDEX ix_movimientohistorial_idmovimiento ON movimientohistorial(idmovimiento);

ALTER TABLE movimiento ENABLE ROW LEVEL SECURITY;
ALTER TABLE cortepormovimiento ENABLE ROW LEVEL SECURITY;
ALTER TABLE movimientohistorial ENABLE ROW LEVEL SECURITY;

CREATE POLICY movimiento_rls ON movimiento FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

CREATE POLICY cortepormovimiento_rls ON cortepormovimiento FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

CREATE POLICY movimientohistorial_rls ON movimientohistorial FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT, UPDATE, DELETE ON movimiento, cortepormovimiento, movimientohistorial TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE movimiento_idmovimiento_seq, cortepormovimiento_idcortemovimiento_seq TO carnisys_user, cs_admin_pg;
