-- Modulo Empleados y Liquidacion de Sueldos (2026-09-29, ver docs/DECISIONS.md).
--
-- Tarifa estandar/de referencia del comercio, NO ligada a ningun empleado. Sirve unicamente como
-- plantilla para proponer valores al dar de alta un empleado (boton "Copiar tarifa estandar" en
-- Empleados/Editar) -- el calculo de una liquidacion NUNCA lee esta tabla, solo empleadotarifa.
--
-- Correr conectado a 'carnisys' con el rol carnisys_admin.
CREATE TABLE tarifageneral (
    idtarifageneral integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempresa integer NOT NULL,
    formaliquidacion text NOT NULL,
    turno text,
    diasemana text,
    valor numeric(12,2) NOT NULL,
    vigentedesde date NOT NULL,
    creado timestamp NOT NULL DEFAULT now(),
    creadopor integer
);

CREATE INDEX ix_tarifageneral_empresa_forma ON tarifageneral(idempresa, formaliquidacion, turno, diasemana, vigentedesde DESC);

ALTER TABLE tarifageneral ENABLE ROW LEVEL SECURITY;

CREATE POLICY tarifageneral_rls ON tarifageneral FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT, UPDATE, DELETE ON tarifageneral TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE tarifageneral_idtarifageneral_seq TO carnisys_user, cs_admin_pg;
