-- Etapa 6: bloque CRUD/referencia de Corte.cs -- corte, actualizacioncorte (con RLS),
-- catalogoglobalimportacionproductos (sin RLS, filtrado a nivel app, igual que el origen),
-- formulas, corteporformula (con RLS), alicuotasiva (sin RLS, tabla chica de referencia),
-- tiposproducto (con RLS, con fila global idempresa=0). Verificado contra la base CarniSys
-- real antes de escribir esto (columnas, RLS, FKs) -- ver docs/DECISIONS.md, Etapa 6.
-- Sin FKs explicitas: SQL Server tampoco las tiene en estas tablas.
-- Correr conectado a 'carnisys' con el rol carnisys_admin.

CREATE TABLE corte (
    idcorte integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo bigint,
    corte text,
    tipo text,
    idcortemaestro integer,
    porcentaje double precision,
    preciokg double precision,
    porcentajehueso double precision,
    independiente integer,
    desvioestandar double precision,
    creado timestamp,
    actualizado timestamp,
    mayorista boolean,
    encierrestock boolean,
    promedio double precision,
    habilitado boolean,
    idalicuotaiva integer,
    alicuotaiva double precision,
    ingresorapidoembutido boolean,
    nivel integer,
    pesable boolean,
    puntostock integer,
    idmarca integer,
    idempresa integer NOT NULL DEFAULT 0
);

-- Historial write-only de ediciones de Corte (nadie la lee de vuelta en el codigo, pero
-- addOrEditCorte SI la escribe en cada edicion real -- confirmado contra la base viva,
-- corrige un gap de la exclusion documentada el 2026-08-18). Sin PK, igual que el origen.
CREATE TABLE actualizacioncorte (
    idcorte integer,
    codigo bigint,
    corte text,
    tipo text,
    idcortemaestro integer,
    porcentaje double precision,
    preciokg double precision,
    porcentajehueso double precision,
    independiente integer,
    desvioestandar double precision,
    creado timestamp,
    actualizado timestamp,
    ingresorapidoembutido boolean,
    encierrestock boolean,
    promedio double precision,
    idempresa integer NOT NULL DEFAULT 0
);

-- Staging de importacion del catalogo global (distinta de CatalogoGlobalProducto, el catalogo
-- global real). Sin RLS en el origen -- el aislamiento es solo a nivel app (WHERE IdEmpresa=@).
CREATE TABLE catalogoglobalimportacionproductos (
    idcatalogoglobalimportacionproducto integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempresa integer NOT NULL,
    idproductoglobal integer NOT NULL,
    idproductoempresa integer NOT NULL,
    fechaalta timestamp NOT NULL DEFAULT now(),
    idusuarioalta integer
);

CREATE UNIQUE INDEX ux_catalogoglobalimportacionproductos_empresa_global
    ON catalogoglobalimportacionproductos(idempresa, idproductoglobal);
CREATE UNIQUE INDEX ux_catalogoglobalimportacionproductos_empresa_empresaproducto
    ON catalogoglobalimportacionproductos(idempresa, idproductoempresa);

CREATE TABLE formulas (
    idformula integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idembutido integer,
    creado timestamp,
    creadopor integer,
    actualizado timestamp,
    actualizadopor integer,
    receta text,
    idempresa integer NOT NULL DEFAULT 0
);

CREATE TABLE corteporformula (
    idcorteporformula integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idformula integer NOT NULL,
    idcorte integer,
    porcentaje double precision,
    agregarauto boolean,
    idempresa integer NOT NULL DEFAULT 0
);

-- Tabla de referencia chica, sin idempresa ni RLS en el origen (confirmado).
CREATE TABLE alicuotasiva (
    idiva integer,
    iva double precision,
    orden integer,
    mostrar boolean
);

CREATE TABLE tiposproducto (
    tipo text,
    orden integer,
    reservadosistema boolean,
    creado timestamp,
    actualizado timestamp,
    idempresa integer NOT NULL DEFAULT 0
);

CREATE INDEX ix_corte_idempresa ON corte(idempresa);
CREATE INDEX ix_actualizacioncorte_idempresa ON actualizacioncorte(idempresa);
CREATE INDEX ix_formulas_idempresa ON formulas(idempresa);
CREATE INDEX ix_corteporformula_idempresa ON corteporformula(idempresa);
CREATE INDEX ix_tiposproducto_idempresa ON tiposproducto(idempresa);

ALTER TABLE corte ENABLE ROW LEVEL SECURITY;
ALTER TABLE actualizacioncorte ENABLE ROW LEVEL SECURITY;
ALTER TABLE formulas ENABLE ROW LEVEL SECURITY;
ALTER TABLE corteporformula ENABLE ROW LEVEL SECURITY;
ALTER TABLE tiposproducto ENABLE ROW LEVEL SECURITY;
-- catalogoglobalimportacionproductos y alicuotasiva: SIN RLS, fiel al origen.

CREATE POLICY corte_rls ON corte FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

CREATE POLICY actualizacioncorte_rls ON actualizacioncorte FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

CREATE POLICY formulas_rls ON formulas FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

CREATE POLICY corteporformula_rls ON corteporformula FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

CREATE POLICY tiposproducto_rls ON tiposproducto FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT, UPDATE, DELETE ON corte, actualizacioncorte, catalogoglobalimportacionproductos,
    formulas, corteporformula, alicuotasiva, tiposproducto TO carnisys_user, cs_admin_pg;
-- Nota: el nombre de secuencia autogenerado de catalogoglobalimportacionproductos supera el
-- limite de 63 caracteres de Postgres y queda truncado
-- (catalogoglobalimportacionprod_idcatalogoglobalimportacionpr_seq, verificado post-creacion).
GRANT USAGE, SELECT ON SEQUENCE corte_idcorte_seq,
    catalogoglobalimportacionprod_idcatalogoglobalimportacionpr_seq,
    formulas_idformula_seq, corteporformula_idcorteporformula_seq TO carnisys_user, cs_admin_pg;
