-- Etapa 13d: bloque Auditoria de ubicacion de Usuario.cs, ultima sub-etapa (cierra Usuario.cs
-- 19/19 metodos). Tabla nueva -- 11 columnas, identity nativa, 108 filas reales.
--
-- Sin idempresa propio (confirmado en dbo.LoginUbicacionLog, columnas verificadas) -- el
-- aislamiento por tenant en obtenerLoginUbicacionLog es via JOIN a usuarios.idempresa (usuarios
-- no tiene RLS, ver Etapa 13a). Por eso esta tabla tampoco necesita RLS propia: no hay columna
-- para filtrar. Distinto motivo que usuarios/usuariopasswordresettokens (esas SI tienen
-- idEmpresa pero se omite RLS a proposito); aca directamente no aplica.
CREATE TABLE loginubicacionlog (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idusuario integer NOT NULL,
    idsucursal integer NOT NULL,
    fechahora timestamp NOT NULL,
    latitud numeric(10,7),
    longitud numeric(10,7),
    precisionmetros numeric(10,2),
    distanciametros numeric(10,2),
    permitido boolean NOT NULL,
    motivo text,
    ip text
);

CREATE INDEX ix_loginubicacionlog_idusuario ON loginubicacionlog(idusuario);
CREATE INDEX ix_loginubicacionlog_fechahora ON loginubicacionlog(fechahora);

GRANT SELECT, INSERT ON loginubicacionlog TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE loginubicacionlog_id_seq TO carnisys_user, cs_admin_pg;
