-- Etapa 13c: bloque Recuperacion de contrasena de Usuario.cs. Tabla nueva -- 11 columnas,
-- identity nativa desde el CREATE (a diferencia de "usuarios" en la Etapa 13a, esta tabla no
-- tenia stub previo).
--
-- SIN RLS, mismo criterio que "usuarios" (Etapa 13a) y por el mismo motivo raiz: confirmado
-- con el usuario. ObtenerTokenRecuperacion busca por tokenHash, sin filtro de idEmpresa --
-- el link de recuperacion de contrasena llega por mail a un usuario anonimo (sin sesion,
-- sin tenant conocido todavia) que hace click y llega directo a ResetPassword con el token
-- en la URL. Verificado contra la base real: dbo.UsuarioPasswordResetTokens tampoco tiene RLS
-- (sys.security_policies, 0 filas), aunque la tabla tiene idEmpresa. El aislamiento por tenant
-- para esta tabla se resuelve implicitamente: el token en si es la credencial (hash aleatorio,
-- un solo uso, con expiracion), no idEmpresa.
CREATE TABLE usuariopasswordresettokens (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idusuario integer NOT NULL,
    idempresa integer NOT NULL DEFAULT 0,
    tokenhash text NOT NULL,
    fechacreacionutc timestamp NOT NULL,
    fechaexpiracionutc timestamp NOT NULL,
    usado boolean NOT NULL DEFAULT false,
    fechausoutc timestamp,
    identificadorsolicitado text,
    emaildestino text,
    proposito text NOT NULL DEFAULT 'reset'
);

CREATE INDEX ix_usuariopasswordresettokens_tokenhash ON usuariopasswordresettokens(tokenhash);

GRANT SELECT, INSERT, UPDATE ON usuariopasswordresettokens TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE usuariopasswordresettokens_id_seq TO carnisys_user, cs_admin_pg;
