-- Etapa 11a: Corte.cs, bloque Embutido -- embutidos, corteporembutido. Verificado contra la
-- base CarniSys real antes de escribir esto (columnas, identity, RLS). Sin FKs explicitas:
-- SQL Server tampoco las tiene.
-- Correr conectado a 'carnisys' con el rol carnisys_admin.

CREATE TABLE embutidos (
    idembutido integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fechaembutido timestamp,
    idcorte integer,
    idsucursal integer,
    observaciones text,
    estado text,
    creado timestamp,
    creadopor integer,
    actualizado timestamp,
    actualizadopor integer,
    idempresa integer NOT NULL DEFAULT 0
);

CREATE TABLE corteporembutido (
    idcorteembutido integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idembutido integer NOT NULL,
    idcorte integer NOT NULL,
    kgutilizados double precision,
    pesobalanza boolean,
    idempresa integer NOT NULL DEFAULT 0
);

CREATE INDEX ix_embutidos_idempresa ON embutidos(idempresa);
CREATE INDEX ix_corteporembutido_idempresa ON corteporembutido(idempresa);
CREATE INDEX ix_corteporembutido_idembutido ON corteporembutido(idembutido);

ALTER TABLE embutidos ENABLE ROW LEVEL SECURITY;
ALTER TABLE corteporembutido ENABLE ROW LEVEL SECURITY;

CREATE POLICY embutidos_rls ON embutidos FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

CREATE POLICY corteporembutido_rls ON corteporembutido FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT, UPDATE, DELETE ON embutidos, corteporembutido TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE embutidos_idembutido_seq, corteporembutido_idcorteembutido_seq TO carnisys_user, cs_admin_pg;
