-- Segunda entidad del piloto (Etapa 3): sucursal (RLS) + empresas (sin RLS, tabla maestra).
-- Correr conectado a la base 'carnisys' ya existente, con el rol carnisys_admin.
-- Sin FK sucursal.idempresa -> empresas.idempresa: SQL Server tampoco la tiene
-- (confirmado en docs/08-relevamiento/snapshot-2026-08-18/schema-columnas.txt), fidelidad
-- al esquema real, mismo criterio que con personas.idiva en la Etapa 2.

CREATE TABLE empresas (
    idempresa integer PRIMARY KEY,
    razonsocialafip text,
    cuit bigint,
    nombrefantasia text,
    slogan1 text,
    slogan2 text,
    slogan3 text,
    iibb bigint,
    condicioniva text,
    inicioactividad date,
    tenantslug text,
    domicilio text,
    ciudad text,
    pais text,
    telefono text,
    email text,
    basepath text,
    esrrii boolean NOT NULL DEFAULT false,
    nombrecertificado_pfx text,
    entorno_homo_prod text,
    basedatosnombre text,
    activa smallint NOT NULL DEFAULT 0
);

CREATE TABLE sucursal (
    idsucursal integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sucursal text,
    idempresa integer NOT NULL DEFAULT 0,
    codpuntoventaafip integer,
    direccion text,
    localidad text,
    provincia text,
    pais text,
    latitud numeric(10,7),
    longitud numeric(10,7),
    radiologinmetros integer NOT NULL DEFAULT 200,
    validarubicacionlogin boolean NOT NULL DEFAULT false
);

CREATE INDEX ix_sucursal_idempresa ON sucursal(idempresa);

ALTER TABLE sucursal ENABLE ROW LEVEL SECURITY;

CREATE POLICY sucursal_rls ON sucursal
    FOR ALL
    USING (
        current_setting('app.id_empresa', true) IS NOT NULL
        AND current_setting('app.id_empresa', true) <> ''
        AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0)
    )
    WITH CHECK (
        idempresa = current_setting('app.id_empresa', true)::int
    );

GRANT SELECT, INSERT, UPDATE, DELETE ON sucursal, empresas TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE sucursal_idsucursal_seq TO carnisys_user, cs_admin_pg;

-- Migracion de datos: 7 filas de Empresas + 9 de Sucursal desde SQL Server local, preservando
-- IDs exactos (mismo proceso que Personas/Iva en la Etapa 2: export via sqlcmd con
-- EsAdminCarniSys=1, conversion a UTF-8, carga via psql \copy conectado como carnisys_admin).
-- Despues de cargar Sucursal con IDs explicitos:
--   SELECT setval('sucursal_idsucursal_seq', (SELECT MAX(idsucursal) FROM sucursal));
