-- Etapa 12b: bloque Expendios/LineaExpendio de Venta.cs. Expendios/Licencias ya existian
-- (slice minimo de la Etapa 10) -- solo hace falta crear "lineaexpendio".
-- Verificado contra la base CarniSys real antes de escribir esto (columnas, identity, sin RLS
-- explicita en el original -- se agrega igual, mismo criterio estandar del resto de la
-- migracion). pesoBalanza es tinyint en SQL Server (no bit), se mapea a boolean, consistente
-- con Entidades.LineaVenta.PesoBalanza. Correr conectado a 'carnisys' con el rol carnisys_admin.

CREATE TABLE lineaexpendio (
    idlineaexpendio integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idexpendio integer,
    idcorte integer,
    cantkg double precision,
    preciokg double precision,
    pesobalanza boolean,
    idempresa integer NOT NULL DEFAULT 0
);

CREATE INDEX ix_lineaexpendio_idempresa ON lineaexpendio(idempresa);
CREATE INDEX ix_lineaexpendio_idexpendio ON lineaexpendio(idexpendio);

ALTER TABLE lineaexpendio ENABLE ROW LEVEL SECURITY;

CREATE POLICY lineaexpendio_rls ON lineaexpendio FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT, UPDATE, DELETE ON lineaexpendio TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE lineaexpendio_idlineaexpendio_seq TO carnisys_user, cs_admin_pg;
