-- Historial de correcciones/altas manuales de RegistroJornada (2026-09-30, ver docs/DECISIONS.md).
-- Una fila por cada evento (correccion o alta manual), nunca se pisa una entrada anterior -- si la
-- misma marcacion se corrige varias veces, quedan varias fotos. Guarda el estado ANTERIOR al
-- cambio (todo NULL si el evento es un alta manual, no una correccion) mas quien lo hizo, cuando y
-- el motivo.
--
-- tipoevento distingue "AltaManualPropia" (el propio empleado cargo un dia olvidado desde "Mi
-- Jornada") de "AltaManualAdmin"/"Correccion" (hechas por un admin) -- menos verificacion, un
-- admin revisando antes de liquidar necesita saber cual es cual.
--
-- Correr conectado a 'carnisys' con el rol carnisys_admin.
CREATE TABLE registrojornadahistorial (
    idregistrojornadahistorial integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempresa integer NOT NULL,
    idregistrojornada integer NOT NULL,
    idempleado integer NOT NULL,
    fecharegistrojornada date NOT NULL,
    fechaanterior date,
    turnoanterior text,
    horaentradaanterior time,
    horasalidaanterior time,
    cantidadanterior numeric(6,2),
    esferiadoanterior boolean,
    tipoevento text NOT NULL,
    motivo text NOT NULL,
    modificadopor integer NOT NULL,
    fechaevento timestamp NOT NULL DEFAULT now()
);

CREATE INDEX ix_registrojornadahistorial_empresa_empleado ON registrojornadahistorial(idempresa, idempleado, fechaevento DESC);
CREATE INDEX ix_registrojornadahistorial_registro ON registrojornadahistorial(idregistrojornada);

ALTER TABLE registrojornadahistorial ENABLE ROW LEVEL SECURITY;

CREATE POLICY registrojornadahistorial_rls ON registrojornadahistorial FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT, UPDATE, DELETE ON registrojornadahistorial TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE registrojornadahistorial_idregistrojornadahistorial_seq TO carnisys_user, cs_admin_pg;
