-- Etapa 7: bloque Ventas/LineaVenta/TemporalLineaVenta de Venta.cs. Verificado contra la base
-- CarniSys real antes de escribir esto (columnas, RLS, PKs/identity) -- ver docs/DECISIONS.md,
-- Etapa 7. Sin FKs explicitas: SQL Server tampoco las tiene en estas tablas.
-- Correr conectado a 'carnisys' con el rol carnisys_admin.

CREATE TABLE ventas (
    idventa integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idvendedor integer,
    fechaventa timestamp,
    turno text,
    idsucursal integer,
    diafestivo text,
    observaciones text,
    idpersona integer,
    nroremito text,
    estado text,
    creado timestamp,
    actualizado timestamp,
    enctacte boolean,
    formapago text,
    tipocomprobante char(1),
    cuit text,
    email text,
    acumredondeokgs double precision,
    acumredondeoimporte double precision,
    comisiontarjeta double precision,
    pagomixtoefectivo double precision NOT NULL DEFAULT 0,
    idempresa integer NOT NULL DEFAULT 0
);

CREATE TABLE lineaventa (
    idlineaventa integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idventa integer,
    idcorte integer,
    idanulado integer,
    cantkg double precision,
    preciokg double precision,
    pesobalanza boolean,
    bonificacion double precision,
    idlineaventaanulado integer,
    kgsajustetarj double precision,
    porckgsajustetarj double precision,
    ajusteprecio double precision,
    idalicuotaiva integer,
    alicuotaiva double precision,
    idempresa integer NOT NULL DEFAULT 0
);

CREATE TABLE temporallineaventa (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idvendedor integer,
    fechainiciopesada timestamp,
    idcorte integer,
    cantkg numeric,
    preciokg numeric,
    totalcorte numeric,
    ventaencurso boolean,
    idsucursal integer,
    creado timestamp,
    idempresa integer NOT NULL DEFAULT 0
);

CREATE INDEX ix_ventas_idempresa ON ventas(idempresa);
CREATE INDEX ix_lineaventa_idempresa ON lineaventa(idempresa);
CREATE INDEX ix_temporallineaventa_idempresa ON temporallineaventa(idempresa);
CREATE INDEX ix_lineaventa_idventa ON lineaventa(idventa);

ALTER TABLE ventas ENABLE ROW LEVEL SECURITY;
ALTER TABLE lineaventa ENABLE ROW LEVEL SECURITY;
ALTER TABLE temporallineaventa ENABLE ROW LEVEL SECURITY;

CREATE POLICY ventas_rls ON ventas FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

CREATE POLICY lineaventa_rls ON lineaventa FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

CREATE POLICY temporallineaventa_rls ON temporallineaventa FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT, UPDATE, DELETE ON ventas, lineaventa, temporallineaventa TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE ventas_idventa_seq, lineaventa_idlineaventa_seq, temporallineaventa_id_seq TO carnisys_user, cs_admin_pg;
