-- Modulo Empleados y Liquidacion de Sueldos (2026-09-29, ver docs/DECISIONS.md).
--
-- Tarifa vigente de UN empleado especifico (nunca un valor general -- "el sueldo es por
-- empleado"), versionada en el tiempo (APPEND-ONLY: la aplicacion nunca hace UPDATE/DELETE sobre
-- una fila existente, siempre INSERT de una nueva con su propio vigentedesde) y con dos
-- dimensiones opcionales: turno y diasemana (permite, ej., que el sabado de manana pague distinto
-- que el resto de la semana). turno es obligatorio para Jornada/MediaJornada, NULL para
-- Hora/Semana/Quincena/Mes. Ver docs/03-modulos/empleados-y-liquidacion-sueldos.md.
--
-- Correr conectado a 'carnisys' con el rol carnisys_admin.
CREATE TABLE empleadotarifa (
    idempleadotarifa integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempresa integer NOT NULL,
    idempleado integer NOT NULL,
    turno text,
    diasemana text,
    valor numeric(12,2) NOT NULL,
    vigentedesde date NOT NULL,
    creado timestamp NOT NULL DEFAULT now(),
    creadopor integer
);

CREATE INDEX ix_empleadotarifa_empleado ON empleadotarifa(idempleado, turno, diasemana, vigentedesde DESC);

ALTER TABLE empleadotarifa ENABLE ROW LEVEL SECURITY;

CREATE POLICY empleadotarifa_rls ON empleadotarifa FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT, UPDATE, DELETE ON empleadotarifa TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE empleadotarifa_idempleadotarifa_seq TO carnisys_user, cs_admin_pg;
