-- Formula secreta (2026-10-04, ver docs/DECISIONS.md "Formula secreta con re-login").
-- formulas.secreta: si es true, los ingredientes/porcentajes de la formula solo se muestran en
-- WebCore tras un re-login (usuario + clave) de alguien con Permisos.Elaborado.VerFormulas.
-- Default false: ninguna formula existente cambia de comportamiento. Idempotente.
-- Correr como carnisys_admin (dueno de las tablas), ANTES de desplegar el codigo.
ALTER TABLE formulas ADD COLUMN IF NOT EXISTS secreta boolean NOT NULL DEFAULT false;

-- Auditoria de acceso a formulas secretas (CLAUDE.md 9.3). Append-only: solo INSERT/SELECT, nunca se borra.
--   tipo            : VER | OCULTAR | FALLO | MARCAR_SECRETA | QUITAR_SECRETA
--   idusuario       : usuario que se autentico en el step-up (quien VE la formula); null en FALLO si
--                     el usuario tipeado no existe
--   idusuariosesion : usuario logueado en la sesion que opera la pantalla (quien pidio verla)
--   idcorte         : producto elaborado (formulas.idembutido guarda el idcorte)
--   detalle         : texto corto (motivo del fallo, etc.); nunca claves ni datos personales
CREATE TABLE IF NOT EXISTS auditoriaformulas (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempresa           integer NOT NULL,
    tipo                varchar(20) NOT NULL,
    idusuario           integer,
    idusuariosesion     integer,
    idcorte             integer,
    ip                  varchar(64),
    fecha               timestamp NOT NULL DEFAULT now(),
    detalle             varchar(300),
    CONSTRAINT ck_auditoriaformulas_tipo CHECK (tipo IN ('VER', 'OCULTAR', 'FALLO', 'MARCAR_SECRETA', 'QUITAR_SECRETA'))
);

CREATE INDEX IF NOT EXISTS ix_auditoriaformulas_empresa_fecha ON auditoriaformulas (idempresa, fecha);

ALTER TABLE auditoriaformulas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS auditoriaformulas_rls ON auditoriaformulas;
CREATE POLICY auditoriaformulas_rls ON auditoriaformulas FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND idempresa = current_setting('app.id_empresa', true)::int)
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT ON auditoriaformulas TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE auditoriaformulas_id_seq TO carnisys_user, cs_admin_pg;
