-- Etapa: CortePuntoStockSucursal.cs (segundo de los modulos chicos 0%-migrados, tras
-- Parametros.cs). Punto de stock propio por combinacion Producto (Corte) x Sucursal. 3
-- metodos: CrearParaTodasLasSucursales, GuardarPuntosStockLote, FindPorSucursal.
--
-- Hallazgo antes de migrar: Negocio/Corte.cs (ya migrado, Etapa 11c) usaba
-- Datos.CortePuntoStockSucursal hardcodeado a SQL Server en sus 2 constructores -- los
-- reportes de stock (FindPorSucursal, via CierreStockWeb/ObtenerExistenciaPorSucursalesPlano)
-- siempre leian de SQL Server aunque el resto de Corte corriera contra Postgres. Confirmado
-- con el usuario: se cierra el gap en el mismo cambio -- Negocio/Corte.cs ahora acepta un
-- ICortePuntoStockSucursalRepository opcional en su constructor Postgres (default null =
-- mismo comportamiento SQL Server de siempre, los 4 call-sites existentes no cambian).
--
-- idcortepuntostocksucursal: identity nativa (en SQL Server tambien es identity real, sin
-- workaround que corregir esta vez). Tiene idEmpresa: SIN RLS en SQL Server (verificado, 0
-- filas en sys.security_policies) -- mismo patron ya encontrado en empresaparametros (etapa
-- anterior): no es un caso "usuarios" (tenant siempre conocido al llamar), simplemente nunca
-- se le agrego RLS en el original. Se agrega RLS estandar en Postgres como mejora deliberada,
-- mismo criterio ya confirmado con el usuario para empresaparametros.
CREATE TABLE cortepuntostocksucursal (
    idcortepuntostocksucursal integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempresa integer NOT NULL,
    idcorte integer NOT NULL,
    idsucursal integer NOT NULL,
    puntostock integer NOT NULL,
    creado timestamp NOT NULL DEFAULT now(),
    actualizado timestamp
);

CREATE UNIQUE INDEX ux_cortepuntostocksucursal_empresa_corte_sucursal ON cortepuntostocksucursal(idempresa, idcorte, idsucursal);
CREATE INDEX ix_cortepuntostocksucursal_sucursal ON cortepuntostocksucursal(idsucursal);

ALTER TABLE cortepuntostocksucursal ENABLE ROW LEVEL SECURITY;

CREATE POLICY cortepuntostocksucursal_rls ON cortepuntostocksucursal FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT, UPDATE, DELETE ON cortepuntostocksucursal TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE cortepuntostocksucursal_idcortepuntostocksucursal_seq TO carnisys_user, cs_admin_pg;
