-- Modulo Empleados y Liquidacion de Sueldos (2026-09-29, ver docs/DECISIONS.md).
--
-- Marcacion de trabajo de un empleado. Solo aplica a formaliquidacion en {Hora, MediaJornada,
-- Jornada} (empleado.RequiereRegistroJornada) -- Semana/Quincena/Mes cobran el fijo del periodo
-- sin marcar asistencia (decision MVP).
--
-- iddispositivoseguro: desde que dispositivo habilitado se fichó (Jornadas/Fichaje), NULL si se
-- cargo manualmente desde una pantalla admin -- ver 20260929g-Alter_dispositivosseguros_add_habilitadofichaje.sql.
-- motivocorreccion / actualizado no nulos: el registro fue corregido despues de la carga inicial,
-- dispara la advertencia "Correcciones pendientes de revisar" al admin.
--
-- Correr conectado a 'carnisys' con el rol carnisys_admin.
CREATE TABLE registrojornada (
    idregistrojornada integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempresa integer NOT NULL,
    idempleado integer NOT NULL,
    fecha date NOT NULL,
    turno text,
    horaentrada time,
    horasalida time,
    cantidad numeric(6,2),
    registradopor integer NOT NULL,
    iddispositivoseguro integer,
    motivocorreccion text,
    creado timestamp NOT NULL DEFAULT now(),
    actualizado timestamp,
    actualizadopor integer
);

CREATE INDEX ix_registrojornada_empleado_fecha ON registrojornada(idempleado, fecha);
CREATE INDEX ix_registrojornada_correcciones ON registrojornada(idempresa, idempleado) WHERE actualizado IS NOT NULL OR motivocorreccion IS NOT NULL;

ALTER TABLE registrojornada ENABLE ROW LEVEL SECURITY;

CREATE POLICY registrojornada_rls ON registrojornada FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT, UPDATE, DELETE ON registrojornada TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE registrojornada_idregistrojornada_seq TO carnisys_user, cs_admin_pg;
