-- Auditoria de cierres de caja (2026-10-06, ver docs/DECISIONS.md "Cambios en cajas cerradas y reapertura").
--  - MODIFICACION: se altero (alta con fecha pasada, modificacion o eliminacion) una venta, compra, pago/cobro o
--    egreso de caja que cae DENTRO de una caja ya cerrada (idcierrecaja). El cierre guardado (ventas, gastos,
--    diferencia) queda desactualizado: el historial y el modal de cierre muestran este aviso.
--  - REAPERTURA: el encargado reabrio la ultima caja cerrada de un usuario; el detalle guarda lo que se deshizo
--    (importes del cierre, conteo del cajero) y el motivo.
-- Append-only: solo INSERT/SELECT, lo registrado no se puede alterar ni borrar.
-- Aditiva e idempotente. Base unica multi-tenant (RLS por idempresa): una sola corrida cubre a todas las empresas.
-- ORDEN DE DEPLOY: correr ESTA migracion ANTES de publicar el codigo nuevo (findCierreCaja y ObtenerDatosCierre
-- la consultan). Correr conectado a 'carnisys' con el rol carnisys_admin (dueno de las tablas).

CREATE TABLE IF NOT EXISTS auditoriacierrecaja (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempresa           integer NOT NULL,
    idcierrecaja        integer NOT NULL,
    tipo                varchar(20) NOT NULL,
    origen              varchar(20),
    idorigen            integer,
    accion              varchar(20),
    idusuario           integer NOT NULL,
    usuario             text,
    fecha               timestamp NOT NULL DEFAULT now(),
    importeanterior     double precision,
    importenuevo        double precision,
    formapagoanterior   text,
    formapagonueva      text,
    detalle             text,
    CONSTRAINT ck_auditoriacierrecaja_tipo CHECK (tipo IN ('MODIFICACION', 'REAPERTURA')),
    CONSTRAINT ck_auditoriacierrecaja_origen CHECK (origen IS NULL OR origen IN ('VENTA', 'COMPRA', 'PAGO', 'EGRESO')),
    CONSTRAINT ck_auditoriacierrecaja_accion CHECK (accion IS NULL OR accion IN ('ALTA', 'MODIFICACION', 'ELIMINACION'))
);

CREATE INDEX IF NOT EXISTS ix_auditoriacierrecaja_cierre ON auditoriacierrecaja (idempresa, idcierrecaja, fecha);

ALTER TABLE auditoriacierrecaja ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS auditoriacierrecaja_rls ON auditoriacierrecaja;
CREATE POLICY auditoriacierrecaja_rls ON auditoriacierrecaja FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND idempresa = current_setting('app.id_empresa', true)::int)
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT ON auditoriacierrecaja TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE auditoriacierrecaja_id_seq TO carnisys_user, cs_admin_pg;
