-- Modulo Empleados y Liquidacion de Sueldos (2026-09-29, ver docs/DECISIONS.md).
--
-- Periodo de vacaciones de un empleado. Efectos (ver Negocio/LiquidacionSueldo.cs y
-- Entidades/EmpleadoVacacion.cs): "Mi Jornada" no exige marcacion esos dias, y el calculo de
-- liquidacion agrega automaticamente una linea "Vacaciones (N dias)" por esos dias. Calculo
-- simplificado, no reproduce la formula legal exacta de la LCT art. 155.
--
-- Correr conectado a 'carnisys' con el rol carnisys_admin.
CREATE TABLE empleadovacacion (
    idempleadovacacion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempresa integer NOT NULL,
    idempleado integer NOT NULL,
    fechadesde date NOT NULL,
    fechahasta date NOT NULL,
    observaciones text,
    creado timestamp NOT NULL DEFAULT now(),
    creadopor integer
);

CREATE INDEX ix_empleadovacacion_empleado ON empleadovacacion(idempleado, fechadesde, fechahasta);

ALTER TABLE empleadovacacion ENABLE ROW LEVEL SECURITY;

CREATE POLICY empleadovacacion_rls ON empleadovacacion FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT, UPDATE, DELETE ON empleadovacacion TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE empleadovacacion_idempleadovacacion_seq TO carnisys_user, cs_admin_pg;
