-- Pagos/cobros: eliminacion logica (con contra-asiento en cta cte) y auditoria de cambios de persona
-- (2026-09-24, ver docs/DECISIONS.md "Pagos: listado, cambio de persona y eliminacion").
-- Correr como carnisys_admin (dueno de las tablas), ANTES de desplegar el codigo.
-- Un pago eliminado NUNCA se borra: queda con eliminado = true y su asiento opuesto en movctacte.

ALTER TABLE pagos
    ADD COLUMN IF NOT EXISTS eliminado          boolean   NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS eliminadopor       integer,
    ADD COLUMN IF NOT EXISTS fechaeliminacion   timestamp,
    ADD COLUMN IF NOT EXISTS motivoeliminacion  text;

-- Auditoria append-only de un pago: CAMBIO_PERSONA (persona anterior/nueva) y ELIMINACION (motivo).
-- Solo INSERT/SELECT: lo registrado no se puede alterar ni borrar.
CREATE TABLE IF NOT EXISTS auditoriapagos (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempresa           integer NOT NULL,
    idpago              integer NOT NULL,
    tipo                varchar(20) NOT NULL,
    idpersonaanterior   integer,
    idpersonanueva      integer,
    idusuario           integer NOT NULL,
    fecha               timestamp NOT NULL DEFAULT now(),
    detalle             text,
    CONSTRAINT ck_auditoriapagos_tipo CHECK (tipo IN ('CAMBIO_PERSONA', 'ELIMINACION'))
);

CREATE INDEX IF NOT EXISTS ix_auditoriapagos_pago ON auditoriapagos (idempresa, idpago, fecha);

ALTER TABLE auditoriapagos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS auditoriapagos_rls ON auditoriapagos;
CREATE POLICY auditoriapagos_rls ON auditoriapagos FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND idempresa = current_setting('app.id_empresa', true)::int)
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT ON auditoriapagos TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE auditoriapagos_id_seq TO carnisys_user, cs_admin_pg;
