-- Motor configurable de interpretacion de codigos de barra internos (EAN-13, prefijo interno de
-- balanza 20-29) por empresa. Un solo formato (activo o no) por (idempresa, prefijo): a
-- diferencia de dispositivosseguros (gap conocido, indice simple sin UNIQUE real), aca la
-- unicidad SI se replica como indice UNICO real tambien en Postgres -- decision explicita del
-- usuario. Cambiar el prefijo de un formato existente no esta soportado desde la UI (se da de
-- baja y se crea uno nuevo), asi que no hace falta un mecanismo de "reemplazo" del UNIQUE.
CREATE TABLE formatoscodigobarras (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempresa integer NOT NULL,
    nombre text NOT NULL,
    prefijo smallint NOT NULL CHECK (prefijo BETWEEN 20 AND 29),
    longitudtotal smallint NOT NULL,
    posicioncodigo smallint NOT NULL,
    longitudcodigo smallint NOT NULL,
    posicionvalor smallint NOT NULL,
    longitudvalor smallint NOT NULL,
    tipovalor text NOT NULL CHECK (tipovalor IN ('Precio', 'Cantidad')),
    cantidaddecimales smallint NOT NULL DEFAULT 0,
    activo boolean NOT NULL DEFAULT true,
    prioridad integer NOT NULL DEFAULT 0,
    creadoutc timestamp NOT NULL,
    idusuariocreador integer,
    modificadoutc timestamp,
    idusuariomodificador integer
);

CREATE UNIQUE INDEX ux_formatoscodigobarras_empresa_prefijo ON formatoscodigobarras (idempresa, prefijo);
CREATE INDEX ix_formatoscodigobarras_idempresa ON formatoscodigobarras (idempresa);

ALTER TABLE formatoscodigobarras ENABLE ROW LEVEL SECURITY;

CREATE POLICY formatoscodigobarras_rls ON formatoscodigobarras FOR ALL
    USING (current_setting('app.id_empresa', true) IS NOT NULL AND current_setting('app.id_empresa', true) <> ''
           AND (idempresa = current_setting('app.id_empresa', true)::int OR idempresa = 0))
    WITH CHECK (idempresa = current_setting('app.id_empresa', true)::int);

GRANT SELECT, INSERT, UPDATE, DELETE ON formatoscodigobarras TO carnisys_user, cs_admin_pg;
GRANT USAGE, SELECT ON SEQUENCE formatoscodigobarras_id_seq TO carnisys_user, cs_admin_pg;
