<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Entidades\Entidades.csproj" />
    <ProjectReference Include="..\Contratos\Contratos.csproj" />
    <ProjectReference Include="..\DatosPostgres\DatosPostgres.csproj" />
    <ProjectReference Include="..\Datos\Datos.csproj" />
    <ProjectReference Include="..\Negocio\Negocio.csproj" />
    <ProjectReference Include="..\Utilidades.Core\Utilidades.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
