using System;
using System.Collections.Generic;
using System.Data;
using Npgsql;

namespace DatosPostgres
{
    // Implementacion Postgres del bloque CRUD/login core (Etapa 13a) + Permisos (Etapa 13b) de
    // Contratos.IUsuarioRepository. Recuperacion de contrasena y auditoria de ubicacion quedan
    // fuera -- se agregan en etapas futuras (13c/13d). Ver docs/DECISIONS.md.
    //
    // "usuarios" NO tiene RLS (decision deliberada, confirmada con el usuario): en el momento
    // del login todavia no se sabe a que empresa pertenece el usuario, asi que filtrar por
    // app.id_empresa haria imposible la propia consulta de login. Verificado que SQL Server
    // tampoco tiene RLS sobre Usuarios. El aislamiento por tenant se hace explicito en el SQL
    // de cada metodo que corresponda (igual que el original).
    //
    // "id" es GENERATED BY DEFAULT AS IDENTITY -- el SP original de SQL Server calculaba
    // MAX(id)+1 con UPDLOCK/HOLDLOCK (con un comentario propio marcando el riesgo de
    // concurrencia); decision del usuario: se resuelve de raiz con identity en vez de
    // replicar esa limitacion.
    public class UsuarioPg : Contratos.IUsuarioRepository
    {
        private readonly string _connectionString;
        private readonly int _idEmpresa;
        private readonly Contratos.ISucursalRepository _sucursalRepo;

        public UsuarioPg(string connectionString, int idEmpresa, Contratos.ISucursalRepository sucursalRepo)
        {
            if (string.IsNullOrWhiteSpace(connectionString)) throw new ArgumentNullException(nameof(connectionString));
            _connectionString = connectionString;
            _idEmpresa = idEmpresa;
            _sucursalRepo = sucursalRepo ?? throw new ArgumentNullException(nameof(sucursalRepo));
        }

        #region Helpers

        private static bool ColumnaExiste(NpgsqlDataReader dr, string columna)
        {
            try { return dr.GetOrdinal(columna) >= 0; } catch { return false; }
        }

        private static string GetString(NpgsqlDataReader dr, string columna) =>
            ColumnaExiste(dr, columna) && dr[columna] != DBNull.Value ? Convert.ToString(dr[columna]) : "";

        private static int GetInt(NpgsqlDataReader dr, string columna) =>
            ColumnaExiste(dr, columna) && dr[columna] != DBNull.Value ? Convert.ToInt32(dr[columna]) : 0;

        private static bool GetBool(NpgsqlDataReader dr, string columna) =>
            ColumnaExiste(dr, columna) && dr[columna] != DBNull.Value && Convert.ToBoolean(dr[columna]);

        private Entidades.Usuario MapUsuario(NpgsqlDataReader dr)
        {
            return new Entidades.Usuario
            {
                Id = Convert.ToInt32(dr["id"]),
                Nombre = GetString(dr, "nombre"),
                User = GetString(dr, "usuario"),
                Clave = GetString(dr, "clave"),
                Email = GetString(dr, "email"),
                PasswordHash = GetString(dr, "passwordhash"),
                PasswordSalt = GetString(dr, "passwordsalt"),
                PasswordHashIterations = GetInt(dr, "passwordhashiterations"),
                PasswordUpdatedAtUtc = dr["passwordupdatedatutc"] == DBNull.Value ? (DateTime?)null : Convert.ToDateTime(dr["passwordupdatedatutc"]),
                Admin = GetBool(dr, "admin"),
                Activo = GetBool(dr, "activo"),
                ColorForm = GetString(dr, "colorform"),
                IdSucursal = dr["idsucursaluser"] == DBNull.Value ? 0 : Convert.ToInt32(dr["idsucursaluser"]),
                IdEmpresa = dr["idempresa"] == DBNull.Value ? 0 : Convert.ToInt32(dr["idempresa"]),
                PermitirLoginFueraSucursal = GetBool(dr, "permitirloginfuerasucursal"),
                EsUsuarioProduccion = GetBool(dr, "esusuarioproduccion"),
                IntentosFallidosLogin = GetInt(dr, "intentosfallidoslogin"),
                Bloqueado = GetBool(dr, "bloqueado"),
                FechaBloqueoUtc = dr["fechabloqueoutc"] == DBNull.Value ? (DateTime?)null : Convert.ToDateTime(dr["fechabloqueoutc"])
            };
        }

        #endregion

        public DataTable obtenerUsuarios(bool soloActivos, bool filtroEmpresa = true, bool soloAdmin = false)
        {
            if (soloAdmin)
            {
                return DbPg.DataTable(_connectionString, _idEmpresa,
                    "SELECT * FROM usuarios WHERE usuario = @usuario;",
                    p => p.AddWithValue("usuario", "admin"));
            }

            var where = new List<string>();
            if (filtroEmpresa) where.Add("idempresa = @idEmpresa");
            if (soloActivos) where.Add("activo = true");

            string sql = "SELECT * FROM usuarios" + (where.Count > 0 ? " WHERE " + string.Join(" AND ", where) : "");

            return DbPg.DataTable(_connectionString, _idEmpresa, sql, p => p.AddWithValue("idEmpresa", _idEmpresa));
        }

        public DataTable getUsuarioActivos()
        {
            return DbPg.DataTable(_connectionString, _idEmpresa,
                "SELECT nombre, usuario, clave FROM usuarios WHERE activo = true AND idempresa = @idEmpresa;",
                p => p.AddWithValue("idEmpresa", _idEmpresa));
        }

        public Entidades.Usuario getUsuarioById(int idUsuario)
        {
            var list = DbPg.Reader(_connectionString, _idEmpresa,
                "SELECT * FROM usuarios WHERE id = @id;",
                dr => MapUsuario(dr),
                p => p.AddWithValue("id", idUsuario));

            if (list.Count == 0) return null;

            var usuario = list[0];
            usuario.Sucursal = usuario.IdSucursal > 0 ? _sucursalRepo.findById(usuario.IdSucursal) : null;
            usuario.Empresa = usuario.IdEmpresa > 0 ? _sucursalRepo.findEmpresaById(usuario.IdEmpresa) : null;
            return usuario;
        }

        // Transaccion explicita: alta de usuario + permisos por defecto son atomicos (mismo
        // patron que el SP original, que hace todo en un BEGIN TRAN/COMMIT). Rama de alta usa
        // "INSERT ... RETURNING id" (columna identity) en vez de MAX(id)+1 -- ver comentario de
        // clase. Los 12 formularios/valores por defecto son los mismos que el SP original
        // hardcodea via LEFT JOIN (VALUES ...).
        public void addOrEditUser(Entidades.Usuario oUsuarioE)
        {
            using (var con = ConexionPg.AbrirConTenant(_connectionString, _idEmpresa, out var tx))
            {
                try
                {
                    if (oUsuarioE.Id == 0)
                    {
                        int idSucursal = oUsuarioE.IdSucursal;
                        if (idSucursal <= 0)
                        {
                            using (var cmdSuc = new NpgsqlCommand(
                                "SELECT idsucursal FROM sucursal WHERE idempresa = @idEmpresa ORDER BY idsucursal LIMIT 1;", con, tx))
                            {
                                cmdSuc.Parameters.AddWithValue("idEmpresa", _idEmpresa);
                                object sucObj = cmdSuc.ExecuteScalar();
                                idSucursal = (sucObj == null || sucObj == DBNull.Value) ? 0 : Convert.ToInt32(sucObj);
                            }
                        }

                        if (_idEmpresa <= 0)
                            throw new InvalidOperationException("IdEmpresa invalido.");
                        if (idSucursal <= 0)
                            throw new InvalidOperationException("No existe sucursal para la empresa indicada.");

                        int nuevoId;
                        using (var cmd = new NpgsqlCommand(@"
                            INSERT INTO usuarios (nombre, usuario, clave, email, admin, activo, colorform, idsucursaluser, idempresa)
                            VALUES (@nombre, @usuario, @clave, @email, @admin, @activo, @colorForm, @idSucursal, @idEmpresa)
                            RETURNING id;", con, tx))
                        {
                            cmd.Parameters.AddWithValue("nombre", oUsuarioE.Nombre ?? "");
                            cmd.Parameters.AddWithValue("usuario", oUsuarioE.User ?? "");
                            cmd.Parameters.AddWithValue("clave", oUsuarioE.Clave ?? "");
                            cmd.Parameters.AddWithValue("email", oUsuarioE.Email ?? "");
                            cmd.Parameters.AddWithValue("admin", oUsuarioE.Admin);
                            cmd.Parameters.AddWithValue("activo", oUsuarioE.Activo);
                            cmd.Parameters.AddWithValue("colorForm", oUsuarioE.ColorForm ?? "");
                            cmd.Parameters.AddWithValue("idSucursal", idSucursal);
                            cmd.Parameters.AddWithValue("idEmpresa", _idEmpresa);
                            nuevoId = Convert.ToInt32(cmd.ExecuteScalar());
                        }

                        oUsuarioE.Id = nuevoId;

                        using (var cmdPerm = new NpgsqlCommand(@"
                            INSERT INTO permisosusuarios (idusuario, idform, diaspermitidosver, diaspermitidoseditar, soloregistrospropios, idempresa)
                            SELECT
                                @id,
                                f.idform,
                                COALESCE(v.diasver, -1),
                                COALESCE(v.diaseditar, -1),
                                COALESCE(v.propios, true),
                                @idEmpresa
                            FROM formularios f
                            LEFT JOIN (VALUES
                                (3,  -1,  0, true),
                                (10, -1,  0, true),
                                (19,  0,  0, false),
                                (21,  0, -1, false),
                                (1,   0,  0, false),
                                (2,  -1,  0, false),
                                (32,  0, -1, false),
                                (18, 14,  0, true),
                                (33,  0,  0, true),
                                (34,  0,  0, true),
                                (5,   0,  0, false),
                                (12, -1,  0, false)
                            ) AS v(idform, diasver, diaseditar, propios)
                                ON f.idform = v.idform;", con, tx))
                        {
                            cmdPerm.Parameters.AddWithValue("id", nuevoId);
                            cmdPerm.Parameters.AddWithValue("idEmpresa", _idEmpresa);
                            cmdPerm.ExecuteNonQuery();
                        }
                    }
                    else
                    {
                        using (var cmd = new NpgsqlCommand(@"
                            UPDATE usuarios SET
                                nombre = @nombre,
                                usuario = @usuario,
                                clave = @clave,
                                email = @email,
                                admin = @admin,
                                activo = @activo,
                                colorform = @colorForm
                            WHERE id = @id;", con, tx))
                        {
                            cmd.Parameters.AddWithValue("id", oUsuarioE.Id);
                            cmd.Parameters.AddWithValue("nombre", oUsuarioE.Nombre ?? "");
                            cmd.Parameters.AddWithValue("usuario", oUsuarioE.User ?? "");
                            cmd.Parameters.AddWithValue("clave", oUsuarioE.Clave ?? "");
                            cmd.Parameters.AddWithValue("email", oUsuarioE.Email ?? "");
                            cmd.Parameters.AddWithValue("admin", oUsuarioE.Admin);
                            cmd.Parameters.AddWithValue("activo", oUsuarioE.Activo);
                            cmd.Parameters.AddWithValue("colorForm", oUsuarioE.ColorForm ?? "");
                            cmd.ExecuteNonQuery();
                        }
                    }

                    tx.Commit();
                }
                catch
                {
                    try { tx.Rollback(); } catch { }
                    throw;
                }
            }
        }

        public void setSucursalUsuario(Entidades.Usuario oUsuario)
        {
            DbPg.NonQuery(_connectionString, _idEmpresa,
                "UPDATE usuarios SET idsucursaluser = @idSucursal WHERE id = @idUsuario;",
                p =>
                {
                    p.AddWithValue("idUsuario", oUsuario.Id);
                    p.AddWithValue("idSucursal", oUsuario.IdSucursal);
                });
        }

        public void setPermitirLoginFueraSucursal(Entidades.Usuario oUsuario)
        {
            DbPg.NonQuery(_connectionString, _idEmpresa,
                "UPDATE usuarios SET permitirloginfuerasucursal = @permitir WHERE id = @idUsuario;",
                p =>
                {
                    p.AddWithValue("idUsuario", oUsuario.Id);
                    p.AddWithValue("permitir", oUsuario.PermitirLoginFueraSucursal);
                });
        }

        public void setEsUsuarioProduccion(Entidades.Usuario oUsuario)
        {
            DbPg.NonQuery(_connectionString, _idEmpresa,
                "UPDATE usuarios SET esusuarioproduccion = @esUsuarioProduccion WHERE id = @idUsuario;",
                p =>
                {
                    p.AddWithValue("idUsuario", oUsuario.Id);
                    p.AddWithValue("esUsuarioProduccion", oUsuario.EsUsuarioProduccion);
                });
        }

        public void ActualizarEstadoBloqueoLogin(Entidades.Usuario oUsuario)
        {
            DbPg.NonQuery(_connectionString, _idEmpresa, @"
                UPDATE usuarios SET
                    intentosfallidoslogin = @intentosFallidosLogin,
                    bloqueado = @bloqueado,
                    fechabloqueoutc = @fechaBloqueoUtc
                WHERE id = @idUsuario;",
                p =>
                {
                    p.AddWithValue("idUsuario", oUsuario.Id);
                    p.AddWithValue("intentosFallidosLogin", oUsuario.IntentosFallidosLogin);
                    p.AddWithValue("bloqueado", oUsuario.Bloqueado);
                    p.AddWithValue("fechaBloqueoUtc", (object)oUsuario.FechaBloqueoUtc ?? DBNull.Value);
                });
        }

        public List<Entidades.Usuario> BuscarUsuariosPorIdentificador(string identificador, bool soloActivos)
        {
            identificador = (identificador ?? string.Empty).Trim();
            if (identificador.Length == 0)
                return new List<Entidades.Usuario>();

            return DbPg.Reader(_connectionString, _idEmpresa, @"
                SELECT *
                FROM usuarios
                WHERE (@soloActivos = false OR activo = true)
                  AND (
                    LOWER(COALESCE(usuario, '')) = LOWER(@identificador)
                    OR LOWER(COALESCE(email, '')) = LOWER(@identificador)
                  )
                ORDER BY activo DESC, id ASC;",
                dr => MapUsuario(dr),
                p =>
                {
                    p.AddWithValue("identificador", identificador);
                    p.AddWithValue("soloActivos", soloActivos);
                });
        }

        public void ActualizarPasswordSeguro(int idUsuario, string claveLegacy, string passwordHash, string passwordSalt, int passwordHashIterations)
        {
            DbPg.NonQuery(_connectionString, _idEmpresa, @"
                UPDATE usuarios SET
                    clave = @clave,
                    passwordhash = @passwordHash,
                    passwordsalt = @passwordSalt,
                    passwordhashiterations = @passwordHashIterations,
                    passwordupdatedatutc = now()
                WHERE id = @idUsuario;",
                p =>
                {
                    p.AddWithValue("idUsuario", idUsuario);
                    p.AddWithValue("clave", claveLegacy ?? string.Empty);
                    p.AddWithValue("passwordHash", passwordHash ?? string.Empty);
                    p.AddWithValue("passwordSalt", passwordSalt ?? string.Empty);
                    p.AddWithValue("passwordHashIterations", passwordHashIterations);
                });
        }

        public void ActualizarPasswordWebSeguro(int idUsuario, string passwordHash, string passwordSalt, int passwordHashIterations)
        {
            DbPg.NonQuery(_connectionString, _idEmpresa, @"
                UPDATE usuarios SET
                    passwordhash = @passwordHash,
                    passwordsalt = @passwordSalt,
                    passwordhashiterations = @passwordHashIterations,
                    passwordupdatedatutc = now()
                WHERE id = @idUsuario;",
                p =>
                {
                    p.AddWithValue("idUsuario", idUsuario);
                    p.AddWithValue("passwordHash", passwordHash ?? string.Empty);
                    p.AddWithValue("passwordSalt", passwordSalt ?? string.Empty);
                    p.AddWithValue("passwordHashIterations", passwordHashIterations);
                });
        }

        public List<Entidades.PermisosUsuarios> getPermisosUsuario(int idUsuario)
        {
            return DbPg.Reader(_connectionString, _idEmpresa, @"
                SELECT
                    f.idform,
                    f.nombreform,
                    f.descripcion,
                    f.formconsulta,
                    f.formedicion,
                    f.formedicionextra1,
                    f.formedicionextra2,
                    COALESCE(p.diaspermitidosver, -1) AS diaspermitidosver,
                    COALESCE(p.diaspermitidoseditar, -1) AS diaspermitidoseditar,
                    COALESCE(p.soloregistrospropios, true) AS soloregistrospropios
                FROM formularios f
                LEFT JOIN permisosusuarios p
                    ON f.idform = p.idform AND p.idusuario = @idUsuario
                ORDER BY f.idform;",
                dr => new Entidades.PermisosUsuarios
                {
                    IdUsuario = idUsuario,
                    IdForm = Convert.ToInt32(dr["idform"]),
                    DiasPermitidosVer = Convert.ToInt32(dr["diaspermitidosver"]),
                    DiasPermitidosEditar = Convert.ToInt32(dr["diaspermitidoseditar"]),
                    SoloRegistrosPropios = Convert.ToBoolean(dr["soloregistrospropios"]),
                    Formulario = new Entidades.Formulario
                    {
                        IdForm = Convert.ToInt32(dr["idform"]),
                        NombreForm = GetString(dr, "nombreform"),
                        Descripcion = GetString(dr, "descripcion"),
                        FormConsulta = GetString(dr, "formconsulta"),
                        FormEdicion = GetString(dr, "formedicion"),
                        FormEdicionExtra1 = GetString(dr, "formedicionextra1"),
                        FormEdicionExtra2 = GetString(dr, "formedicionextra2")
                    }
                },
                p => p.AddWithValue("idUsuario", idUsuario));
        }

        // Upsert nativo de Postgres (ON CONFLICT) en vez del IF EXISTS/UPDATE/INSERT del
        // original -- mismo efecto, una sola sentencia por fila en vez de un SELECT + UPDATE/
        // INSERT. PermisosUsuarios.idEmpresa tiene DEFAULT atado a SESSION_CONTEXT en SQL
        // Server (verificado con sys.default_constraints, mismo patron que Sectores en la
        // Etapa 12a) -- no hay equivalente en Postgres, se bindea @idEmpresa explicito.
        public void AddOrEditPermisos(List<Entidades.PermisosUsuarios> permisos)
        {
            if (permisos == null) throw new ArgumentNullException(nameof(permisos));
            if (permisos.Count == 0) return;

            using (var con = ConexionPg.AbrirConTenant(_connectionString, _idEmpresa, out var tx))
            {
                try
                {
                    using (var cmd = new NpgsqlCommand(@"
                        INSERT INTO permisosusuarios (idusuario, idform, diaspermitidosver, diaspermitidoseditar, soloregistrospropios, idempresa)
                        VALUES (@idUsuario, @idForm, @diasVer, @diasEditar, @soloPropios, @idEmpresa)
                        ON CONFLICT (idusuario, idform) DO UPDATE SET
                            diaspermitidosver = EXCLUDED.diaspermitidosver,
                            diaspermitidoseditar = EXCLUDED.diaspermitidoseditar,
                            soloregistrospropios = EXCLUDED.soloregistrospropios;", con, tx))
                    {
                        cmd.Parameters.Add("idUsuario", NpgsqlTypes.NpgsqlDbType.Integer);
                        cmd.Parameters.Add("idForm", NpgsqlTypes.NpgsqlDbType.Integer);
                        cmd.Parameters.Add("diasVer", NpgsqlTypes.NpgsqlDbType.Integer);
                        cmd.Parameters.Add("diasEditar", NpgsqlTypes.NpgsqlDbType.Integer);
                        cmd.Parameters.Add("soloPropios", NpgsqlTypes.NpgsqlDbType.Boolean);
                        cmd.Parameters.Add("idEmpresa", NpgsqlTypes.NpgsqlDbType.Integer);
                        cmd.Prepare();

                        foreach (var permiso in permisos)
                        {
                            cmd.Parameters["idUsuario"].Value = permiso.IdUsuario;
                            cmd.Parameters["idForm"].Value = permiso.IdForm;
                            cmd.Parameters["diasVer"].Value = permiso.DiasPermitidosVer;
                            cmd.Parameters["diasEditar"].Value = permiso.DiasPermitidosEditar;
                            cmd.Parameters["soloPropios"].Value = permiso.SoloRegistrosPropios;
                            cmd.Parameters["idEmpresa"].Value = _idEmpresa;
                            cmd.ExecuteNonQuery();
                        }
                    }

                    tx.Commit();
                }
                catch
                {
                    try { tx.Rollback(); } catch { }
                    throw;
                }
            }
        }
    }
}
