using System;
using System.Collections.Generic;
using System.Data;
using Npgsql;

namespace DatosPostgres
{
    // Implementacion Postgres del bloque CRUD/login core (Etapa 13a) + Permisos (Etapa 13b) de
    // Contratos.IUsuarioRepository. Recuperacion de contrasena y auditoria de ubicacion quedan
    // fuera -- se agregan en etapas futuras (13c/13d). Ver docs/DECISIONS.md.
    //
    // "usuarios" y "usuariopasswordresettokens" SI tienen RLS (revertido de la decision anterior
    // documentada abajo, ver docs/DECISIONS.md 2026-08-21: se encontro que sin RLS, cualquier
    // query que se olvidara del WHERE idempresa filtraria usuarios de otro tenant, passwordhash
    // incluido -- confiar en que cada caller se acuerde de chequear a mano no escala). El
    // problema real: Login/OlvideMiContrasena/ResetPassword/UnlockAccount corren SIN saber a que
    // empresa pertenece el usuario todavia -- necesitan buscar cruzando todas las empresas. Los
    // pocos metodos que lo necesitan usan AbrirSinRLS (mas abajo, `SET LOCAL ROLE
    // carnisys_usuarios_bypass` scopeado a esa transaccion puntual, ver migracion 20260821b y
    // docs/DECISIONS.md); el resto de la clase sigue protegida por RLS sin cambios.
    //
    // "id" es GENERATED BY DEFAULT AS IDENTITY -- el SP original de SQL Server calculaba
    // MAX(id)+1 con UPDLOCK/HOLDLOCK (con un comentario propio marcando el riesgo de
    // concurrencia); decision del usuario: se resuelve de raiz con identity en vez de
    // replicar esa limitacion.
    public class UsuarioPg : Contratos.IUsuarioRepository
    {
        private readonly string _connectionString;
        private readonly int _idEmpresa;
        private readonly Contratos.ISucursalRepository _sucursalRepo;

        public UsuarioPg(string connectionString, int idEmpresa, Contratos.ISucursalRepository sucursalRepo)
        {
            if (string.IsNullOrWhiteSpace(connectionString)) throw new ArgumentNullException(nameof(connectionString));
            _connectionString = connectionString;
            _idEmpresa = idEmpresa;
            _sucursalRepo = sucursalRepo ?? throw new ArgumentNullException(nameof(sucursalRepo));
        }

        #region Helpers sin RLS (login/recuperacion de contraseña, tenant desconocido)

        // Abre una conexion+transaccion propia asumiendo el rol carnisys_usuarios_bypass (ver
        // migracion 20260821b) -- SOLO para los pocos metodos de esta clase que legitimamente
        // necesitan buscar cruzando todas las empresas (ver comentario de clase).
        //
        // NO usa "SET LOCAL row_security = off": Postgres RECHAZA esa sentencia con error 42501
        // si el rol no tiene ya BYPASSRLS -- no existe forma de desactivar RLS "por esta vez"
        // sin el privilegio real (encontrado probando el login real, ver docs/DECISIONS.md
        // 2026-08-21). SET LOCAL ROLE si funciona: el efecto vive y muere con la transaccion
        // (revierte solo al hacer commit/rollback), igual que app.id_empresa en
        // ConexionPg.AbrirConTenant -- una conexion reciclada por el pool nunca puede arrastrar
        // esto a la proxima request. Verificado a mano que la membresia de carnisys_user en
        // carnisys_usuarios_bypass NO habilita el bypass fuera de este SET LOCAL ROLE explicito.
        private NpgsqlConnection AbrirSinRLS(out NpgsqlTransaction tx)
        {
            var cn = new NpgsqlConnection(_connectionString);
            cn.Open();
            tx = cn.BeginTransaction();
            using (var cmd = new NpgsqlCommand("SET LOCAL ROLE carnisys_usuarios_bypass;", cn, tx))
                cmd.ExecuteNonQuery();
            return cn;
        }

        private void NonQuerySinRLS(string sql, Action<NpgsqlParameterCollection> setParams)
        {
            using (var cn = AbrirSinRLS(out var tx))
            {
                try
                {
                    using (var cmd = new NpgsqlCommand(sql, cn, tx))
                    {
                        setParams?.Invoke(cmd.Parameters);
                        cmd.ExecuteNonQuery();
                    }
                    tx.Commit();
                }
                catch { tx.Rollback(); throw; }
            }
        }

        private List<T> ReaderSinRLS<T>(string sql, Func<NpgsqlDataReader, T> map, Action<NpgsqlParameterCollection> setParams)
        {
            using (var cn = AbrirSinRLS(out var tx))
            {
                try
                {
                    var lista = new List<T>();
                    using (var cmd = new NpgsqlCommand(sql, cn, tx))
                    {
                        setParams?.Invoke(cmd.Parameters);
                        using (var dr = cmd.ExecuteReader())
                        {
                            while (dr.Read())
                                lista.Add(map(dr));
                        }
                    }
                    tx.Commit();
                    return lista;
                }
                catch { tx.Rollback(); throw; }
            }
        }

        private DataTable DataTableSinRLS(string sql, Action<NpgsqlParameterCollection> setParams)
        {
            using (var cn = AbrirSinRLS(out var tx))
            {
                try
                {
                    var dt = new DataTable();
                    using (var cmd = new NpgsqlCommand(sql, cn, tx))
                    using (var da = new NpgsqlDataAdapter(cmd))
                    {
                        setParams?.Invoke(cmd.Parameters);
                        da.Fill(dt);
                    }
                    tx.Commit();
                    return dt;
                }
                catch { tx.Rollback(); throw; }
            }
        }

        #endregion

        #region Helpers

        private static bool ColumnaExiste(NpgsqlDataReader dr, string columna)
        {
            try { return dr.GetOrdinal(columna) >= 0; } catch { return false; }
        }

        private static string GetString(NpgsqlDataReader dr, string columna) =>
            ColumnaExiste(dr, columna) && dr[columna] != DBNull.Value ? Convert.ToString(dr[columna]) : "";

        private static int GetInt(NpgsqlDataReader dr, string columna) =>
            ColumnaExiste(dr, columna) && dr[columna] != DBNull.Value ? Convert.ToInt32(dr[columna]) : 0;

        private static bool GetBool(NpgsqlDataReader dr, string columna) =>
            ColumnaExiste(dr, columna) && dr[columna] != DBNull.Value && Convert.ToBoolean(dr[columna]);

        private Entidades.Usuario MapUsuario(NpgsqlDataReader dr)
        {
            return new Entidades.Usuario
            {
                Id = Convert.ToInt32(dr["id"]),
                Nombre = GetString(dr, "nombre"),
                User = GetString(dr, "usuario"),
                Clave = GetString(dr, "clave"),
                Email = GetString(dr, "email"),
                PasswordHash = GetString(dr, "passwordhash"),
                PasswordSalt = GetString(dr, "passwordsalt"),
                PasswordHashIterations = GetInt(dr, "passwordhashiterations"),
                PasswordUpdatedAtUtc = dr["passwordupdatedatutc"] == DBNull.Value ? (DateTime?)null : Convert.ToDateTime(dr["passwordupdatedatutc"]),
                Admin = GetBool(dr, "admin"),
                Activo = GetBool(dr, "activo"),
                ColorForm = GetString(dr, "colorform"),
                IdSucursal = dr["idsucursaluser"] == DBNull.Value ? 0 : Convert.ToInt32(dr["idsucursaluser"]),
                IdEmpresa = dr["idempresa"] == DBNull.Value ? 0 : Convert.ToInt32(dr["idempresa"]),
                PermitirLoginFueraSucursal = GetBool(dr, "permitirloginfuerasucursal"),
                EsUsuarioProduccion = GetBool(dr, "esusuarioproduccion"),
                IntentosFallidosLogin = GetInt(dr, "intentosfallidoslogin"),
                Bloqueado = GetBool(dr, "bloqueado"),
                FechaBloqueoUtc = dr["fechabloqueoutc"] == DBNull.Value ? (DateTime?)null : Convert.ToDateTime(dr["fechabloqueoutc"])
            };
        }

        #endregion

        public DataTable obtenerUsuarios(bool soloActivos, bool filtroEmpresa = true, bool soloAdmin = false)
        {
            if (soloAdmin)
            {
                // Cruza todas las empresas a proposito -- "admin" es una cuenta global (ver
                // comentario de clase). Sin caller real desde Web hoy (solo Presentacion/
                // WinForms, que nunca toca Postgres), pero implementado igual por las dudas.
                return DataTableSinRLS(
                    "SELECT * FROM usuarios WHERE usuario = @usuario;",
                    p => p.AddWithValue("usuario", "admin"));
            }

            if (!filtroEmpresa)
            {
                // Camino de login: busca cruzando todas las empresas porque todavia no se sabe
                // a cual pertenece el usuario (ver comentario de clase).
                var whereSinFiltro = new List<string>();
                if (soloActivos) whereSinFiltro.Add("activo = true");
                string sqlSinFiltro = "SELECT * FROM usuarios" + (whereSinFiltro.Count > 0 ? " WHERE " + string.Join(" AND ", whereSinFiltro) : "");
                return DataTableSinRLS(sqlSinFiltro, null);
            }

            var where = new List<string>();
            where.Add("idempresa = @idEmpresa");
            if (soloActivos) where.Add("activo = true");

            string sql = "SELECT * FROM usuarios WHERE " + string.Join(" AND ", where);

            return DbPg.DataTable(_connectionString, _idEmpresa, sql, p => p.AddWithValue("idEmpresa", _idEmpresa));
        }

        public DataTable getUsuarioActivos()
        {
            return DbPg.DataTable(_connectionString, _idEmpresa,
                "SELECT nombre, usuario, clave FROM usuarios WHERE activo = true AND idempresa = @idEmpresa;",
                p => p.AddWithValue("idEmpresa", _idEmpresa));
        }

        public Entidades.Usuario getUsuarioById(int idUsuario, bool sinRestriccionDeTenant = false)
        {
            const string sql = "SELECT * FROM usuarios WHERE id = @id;";
            var list = sinRestriccionDeTenant
                ? ReaderSinRLS(sql, dr => MapUsuario(dr), p => p.AddWithValue("id", idUsuario))
                : DbPg.Reader(_connectionString, _idEmpresa, sql, dr => MapUsuario(dr), p => p.AddWithValue("id", idUsuario));

            if (list.Count == 0) return null;

            var usuario = list[0];
            usuario.Sucursal = usuario.IdSucursal > 0 ? _sucursalRepo.findById(usuario.IdSucursal) : null;
            usuario.Empresa = usuario.IdEmpresa > 0 ? _sucursalRepo.findEmpresaById(usuario.IdEmpresa) : null;
            return usuario;
        }

        // Transaccion explicita: alta de usuario + permisos por defecto son atomicos (mismo
        // patron que el SP original, que hace todo en un BEGIN TRAN/COMMIT). Rama de alta usa
        // "INSERT ... RETURNING id" (columna identity) en vez de MAX(id)+1 -- ver comentario de
        // clase. Los 12 formularios/valores por defecto son los mismos que el SP original
        // hardcodea via LEFT JOIN (VALUES ...).
        public void addOrEditUser(Entidades.Usuario oUsuarioE)
        {
            using (var con = ConexionPg.AbrirConTenant(_connectionString, _idEmpresa, out var tx))
            {
                try
                {
                    if (oUsuarioE.Id == 0)
                    {
                        int idSucursal = oUsuarioE.IdSucursal;
                        if (idSucursal <= 0)
                        {
                            using (var cmdSuc = new NpgsqlCommand(
                                "SELECT idsucursal FROM sucursal WHERE idempresa = @idEmpresa ORDER BY idsucursal LIMIT 1;", con, tx))
                            {
                                cmdSuc.Parameters.AddWithValue("idEmpresa", _idEmpresa);
                                object sucObj = cmdSuc.ExecuteScalar();
                                idSucursal = (sucObj == null || sucObj == DBNull.Value) ? 0 : Convert.ToInt32(sucObj);
                            }
                        }

                        if (_idEmpresa <= 0)
                            throw new InvalidOperationException("IdEmpresa invalido.");
                        if (idSucursal <= 0)
                            throw new InvalidOperationException("No existe sucursal para la empresa indicada.");

                        int nuevoId;
                        using (var cmd = new NpgsqlCommand(@"
                            INSERT INTO usuarios (nombre, usuario, clave, email, admin, activo, colorform, idsucursaluser, idempresa)
                            VALUES (@nombre, @usuario, @clave, @email, @admin, @activo, @colorForm, @idSucursal, @idEmpresa)
                            RETURNING id;", con, tx))
                        {
                            cmd.Parameters.AddWithValue("nombre", oUsuarioE.Nombre ?? "");
                            cmd.Parameters.AddWithValue("usuario", oUsuarioE.User ?? "");
                            cmd.Parameters.AddWithValue("clave", oUsuarioE.Clave ?? "");
                            cmd.Parameters.AddWithValue("email", oUsuarioE.Email ?? "");
                            cmd.Parameters.AddWithValue("admin", oUsuarioE.Admin);
                            cmd.Parameters.AddWithValue("activo", oUsuarioE.Activo);
                            cmd.Parameters.AddWithValue("colorForm", oUsuarioE.ColorForm ?? "");
                            cmd.Parameters.AddWithValue("idSucursal", idSucursal);
                            cmd.Parameters.AddWithValue("idEmpresa", _idEmpresa);
                            nuevoId = Convert.ToInt32(cmd.ExecuteScalar());
                        }

                        oUsuarioE.Id = nuevoId;

                        using (var cmdPerm = new NpgsqlCommand(@"
                            INSERT INTO permisosusuarios (idusuario, idform, diaspermitidosver, diaspermitidoseditar, soloregistrospropios, idempresa)
                            SELECT
                                @id,
                                f.idform,
                                COALESCE(v.diasver, -1),
                                COALESCE(v.diaseditar, -1),
                                COALESCE(v.propios, true),
                                @idEmpresa
                            FROM formularios f
                            LEFT JOIN (VALUES
                                (3,  -1,  0, true),
                                (10, -1,  0, true),
                                (19,  0,  0, false),
                                (21,  0, -1, false),
                                (1,   0,  0, false),
                                (2,  -1,  0, false),
                                (32,  0, -1, false),
                                (18, 14,  0, true),
                                (33,  0,  0, true),
                                (34,  0,  0, true),
                                (5,   0,  0, false),
                                (12, -1,  0, false)
                            ) AS v(idform, diasver, diaseditar, propios)
                                ON f.idform = v.idform;", con, tx))
                        {
                            cmdPerm.Parameters.AddWithValue("id", nuevoId);
                            cmdPerm.Parameters.AddWithValue("idEmpresa", _idEmpresa);
                            cmdPerm.ExecuteNonQuery();
                        }
                    }
                    else
                    {
                        using (var cmd = new NpgsqlCommand(@"
                            UPDATE usuarios SET
                                nombre = @nombre,
                                usuario = @usuario,
                                clave = @clave,
                                email = @email,
                                admin = @admin,
                                activo = @activo,
                                colorform = @colorForm
                            WHERE id = @id;", con, tx))
                        {
                            cmd.Parameters.AddWithValue("id", oUsuarioE.Id);
                            cmd.Parameters.AddWithValue("nombre", oUsuarioE.Nombre ?? "");
                            cmd.Parameters.AddWithValue("usuario", oUsuarioE.User ?? "");
                            cmd.Parameters.AddWithValue("clave", oUsuarioE.Clave ?? "");
                            cmd.Parameters.AddWithValue("email", oUsuarioE.Email ?? "");
                            cmd.Parameters.AddWithValue("admin", oUsuarioE.Admin);
                            cmd.Parameters.AddWithValue("activo", oUsuarioE.Activo);
                            cmd.Parameters.AddWithValue("colorForm", oUsuarioE.ColorForm ?? "");
                            cmd.ExecuteNonQuery();
                        }
                    }

                    tx?.Commit();
                }
                catch
                {
                    try { tx?.Rollback(); } catch { }
                    throw;
                }
            }
        }

        public void setSucursalUsuario(Entidades.Usuario oUsuario)
        {
            DbPg.NonQuery(_connectionString, _idEmpresa,
                "UPDATE usuarios SET idsucursaluser = @idSucursal WHERE id = @idUsuario;",
                p =>
                {
                    p.AddWithValue("idUsuario", oUsuario.Id);
                    p.AddWithValue("idSucursal", oUsuario.IdSucursal);
                });
        }

        public void setPermitirLoginFueraSucursal(Entidades.Usuario oUsuario)
        {
            DbPg.NonQuery(_connectionString, _idEmpresa,
                "UPDATE usuarios SET permitirloginfuerasucursal = @permitir WHERE id = @idUsuario;",
                p =>
                {
                    p.AddWithValue("idUsuario", oUsuario.Id);
                    p.AddWithValue("permitir", oUsuario.PermitirLoginFueraSucursal);
                });
        }

        public void setEsUsuarioProduccion(Entidades.Usuario oUsuario)
        {
            DbPg.NonQuery(_connectionString, _idEmpresa,
                "UPDATE usuarios SET esusuarioproduccion = @esUsuarioProduccion WHERE id = @idUsuario;",
                p =>
                {
                    p.AddWithValue("idUsuario", oUsuario.Id);
                    p.AddWithValue("esUsuarioProduccion", oUsuario.EsUsuarioProduccion);
                });
        }

        public void ActualizarEstadoBloqueoLogin(Entidades.Usuario oUsuario, bool sinRestriccionDeTenant = false)
        {
            const string sql = @"
                UPDATE usuarios SET
                    intentosfallidoslogin = @intentosFallidosLogin,
                    bloqueado = @bloqueado,
                    fechabloqueoutc = @fechaBloqueoUtc
                WHERE id = @idUsuario;";
            Action<NpgsqlParameterCollection> setParams = p =>
            {
                p.AddWithValue("idUsuario", oUsuario.Id);
                p.AddWithValue("intentosFallidosLogin", oUsuario.IntentosFallidosLogin);
                p.AddWithValue("bloqueado", oUsuario.Bloqueado);
                p.AddWithValue("fechaBloqueoUtc", (object)oUsuario.FechaBloqueoUtc ?? DBNull.Value);
            };

            if (sinRestriccionDeTenant)
                NonQuerySinRLS(sql, setParams);
            else
                DbPg.NonQuery(_connectionString, _idEmpresa, sql, setParams);
        }

        // Cruza todas las empresas a proposito -- unico caller es "Olvide mi contraseña"
        // (LoginController), sin tenant conocido todavia.
        public List<Entidades.Usuario> BuscarUsuariosPorIdentificador(string identificador, bool soloActivos)
        {
            identificador = (identificador ?? string.Empty).Trim();
            if (identificador.Length == 0)
                return new List<Entidades.Usuario>();

            return ReaderSinRLS(@"
                SELECT *
                FROM usuarios
                WHERE (@soloActivos = false OR activo = true)
                  AND (
                    LOWER(COALESCE(usuario, '')) = LOWER(@identificador)
                    OR LOWER(COALESCE(email, '')) = LOWER(@identificador)
                  )
                ORDER BY activo DESC, id ASC;",
                dr => MapUsuario(dr),
                p =>
                {
                    p.AddWithValue("identificador", identificador);
                    p.AddWithValue("soloActivos", soloActivos);
                });
        }

        // Chequeo global (todas las empresas) de unicidad de nombre de usuario -- el candado de
        // verdad es el indice unico de la migracion 20260821; esto es solo para un mensaje de
        // error legible. Cruza todas las empresas a proposito, igual que BuscarUsuariosPorIdentificador.
        public bool existeUsuario(string usuario, int idExcluir)
        {
            usuario = (usuario ?? "").Trim();
            if (usuario.Length == 0) return false;

            var lista = ReaderSinRLS(
                "SELECT 1 FROM usuarios WHERE LOWER(usuario) = LOWER(@usuario) AND id <> @idExcluir LIMIT 1;",
                dr => true,
                p =>
                {
                    p.AddWithValue("usuario", usuario);
                    p.AddWithValue("idExcluir", idExcluir);
                });
            return lista.Count > 0;
        }

        public void ActualizarPasswordSeguro(int idUsuario, string claveLegacy, string passwordHash, string passwordSalt, int passwordHashIterations)
        {
            DbPg.NonQuery(_connectionString, _idEmpresa, @"
                UPDATE usuarios SET
                    clave = @clave,
                    passwordhash = @passwordHash,
                    passwordsalt = @passwordSalt,
                    passwordhashiterations = @passwordHashIterations,
                    passwordupdatedatutc = now()
                WHERE id = @idUsuario;",
                p =>
                {
                    p.AddWithValue("idUsuario", idUsuario);
                    p.AddWithValue("clave", claveLegacy ?? string.Empty);
                    p.AddWithValue("passwordHash", passwordHash ?? string.Empty);
                    p.AddWithValue("passwordSalt", passwordSalt ?? string.Empty);
                    p.AddWithValue("passwordHashIterations", passwordHashIterations);
                });
        }

        public void ActualizarPasswordWebSeguro(int idUsuario, string passwordHash, string passwordSalt, int passwordHashIterations, bool sinRestriccionDeTenant = false)
        {
            const string sql = @"
                UPDATE usuarios SET
                    passwordhash = @passwordHash,
                    passwordsalt = @passwordSalt,
                    passwordhashiterations = @passwordHashIterations,
                    passwordupdatedatutc = now()
                WHERE id = @idUsuario;";
            Action<NpgsqlParameterCollection> setParams = p =>
            {
                p.AddWithValue("idUsuario", idUsuario);
                p.AddWithValue("passwordHash", passwordHash ?? string.Empty);
                p.AddWithValue("passwordSalt", passwordSalt ?? string.Empty);
                p.AddWithValue("passwordHashIterations", passwordHashIterations);
            };

            if (sinRestriccionDeTenant)
                NonQuerySinRLS(sql, setParams);
            else
                DbPg.NonQuery(_connectionString, _idEmpresa, sql, setParams);
        }

        public List<Entidades.PermisosUsuarios> getPermisosUsuario(int idUsuario)
        {
            return DbPg.Reader(_connectionString, _idEmpresa, @"
                SELECT
                    f.idform,
                    f.nombreform,
                    f.descripcion,
                    f.formconsulta,
                    f.formedicion,
                    f.formedicionextra1,
                    f.formedicionextra2,
                    COALESCE(p.diaspermitidosver, -1) AS diaspermitidosver,
                    COALESCE(p.diaspermitidoseditar, -1) AS diaspermitidoseditar,
                    COALESCE(p.soloregistrospropios, true) AS soloregistrospropios
                FROM formularios f
                LEFT JOIN permisosusuarios p
                    ON f.idform = p.idform AND p.idusuario = @idUsuario
                ORDER BY f.idform;",
                dr => new Entidades.PermisosUsuarios
                {
                    IdUsuario = idUsuario,
                    IdForm = Convert.ToInt32(dr["idform"]),
                    DiasPermitidosVer = Convert.ToInt32(dr["diaspermitidosver"]),
                    DiasPermitidosEditar = Convert.ToInt32(dr["diaspermitidoseditar"]),
                    SoloRegistrosPropios = Convert.ToBoolean(dr["soloregistrospropios"]),
                    Formulario = new Entidades.Formulario
                    {
                        IdForm = Convert.ToInt32(dr["idform"]),
                        NombreForm = GetString(dr, "nombreform"),
                        Descripcion = GetString(dr, "descripcion"),
                        FormConsulta = GetString(dr, "formconsulta"),
                        FormEdicion = GetString(dr, "formedicion"),
                        FormEdicionExtra1 = GetString(dr, "formedicionextra1"),
                        FormEdicionExtra2 = GetString(dr, "formedicionextra2")
                    }
                },
                p => p.AddWithValue("idUsuario", idUsuario));
        }

        // Upsert nativo de Postgres (ON CONFLICT) en vez del IF EXISTS/UPDATE/INSERT del
        // original -- mismo efecto, una sola sentencia por fila en vez de un SELECT + UPDATE/
        // INSERT. PermisosUsuarios.idEmpresa tiene DEFAULT atado a SESSION_CONTEXT en SQL
        // Server (verificado con sys.default_constraints, mismo patron que Sectores en la
        // Etapa 12a) -- no hay equivalente en Postgres, se bindea @idEmpresa explicito.
        public void AddOrEditPermisos(List<Entidades.PermisosUsuarios> permisos)
        {
            if (permisos == null) throw new ArgumentNullException(nameof(permisos));
            if (permisos.Count == 0) return;

            using (var con = ConexionPg.AbrirConTenant(_connectionString, _idEmpresa, out var tx))
            {
                try
                {
                    using (var cmd = new NpgsqlCommand(@"
                        INSERT INTO permisosusuarios (idusuario, idform, diaspermitidosver, diaspermitidoseditar, soloregistrospropios, idempresa)
                        VALUES (@idUsuario, @idForm, @diasVer, @diasEditar, @soloPropios, @idEmpresa)
                        ON CONFLICT (idusuario, idform) DO UPDATE SET
                            diaspermitidosver = EXCLUDED.diaspermitidosver,
                            diaspermitidoseditar = EXCLUDED.diaspermitidoseditar,
                            soloregistrospropios = EXCLUDED.soloregistrospropios;", con, tx))
                    {
                        cmd.Parameters.Add("idUsuario", NpgsqlTypes.NpgsqlDbType.Integer);
                        cmd.Parameters.Add("idForm", NpgsqlTypes.NpgsqlDbType.Integer);
                        cmd.Parameters.Add("diasVer", NpgsqlTypes.NpgsqlDbType.Integer);
                        cmd.Parameters.Add("diasEditar", NpgsqlTypes.NpgsqlDbType.Integer);
                        cmd.Parameters.Add("soloPropios", NpgsqlTypes.NpgsqlDbType.Boolean);
                        cmd.Parameters.Add("idEmpresa", NpgsqlTypes.NpgsqlDbType.Integer);
                        cmd.Prepare();

                        foreach (var permiso in permisos)
                        {
                            cmd.Parameters["idUsuario"].Value = permiso.IdUsuario;
                            cmd.Parameters["idForm"].Value = permiso.IdForm;
                            cmd.Parameters["diasVer"].Value = permiso.DiasPermitidosVer;
                            cmd.Parameters["diasEditar"].Value = permiso.DiasPermitidosEditar;
                            cmd.Parameters["soloPropios"].Value = permiso.SoloRegistrosPropios;
                            cmd.Parameters["idEmpresa"].Value = _idEmpresa;
                            cmd.ExecuteNonQuery();
                        }
                    }

                    tx?.Commit();
                }
                catch
                {
                    try { tx?.Rollback(); } catch { }
                    throw;
                }
            }
        }

        // usuariopasswordresettokens NO tiene RLS (mismo motivo que "usuarios", ver comentario
        // de clase y el script de creacion de la tabla): ObtenerTokenRecuperacion busca por
        // tokenhash desde un link de mail anonimo, sin tenant conocido todavia. Ninguno de
        // estos 4 metodos filtra por idempresa, igual que el original.
        public void CrearTokenRecuperacion(Entidades.UsuarioPasswordResetToken token)
        {
            if (token == null) throw new ArgumentNullException(nameof(token));

            NonQuerySinRLS(@"
                INSERT INTO usuariopasswordresettokens
                (idusuario, idempresa, tokenhash, fechacreacionutc, fechaexpiracionutc, usado, fechausoutc, identificadorsolicitado, emaildestino, proposito)
                VALUES
                (@idUsuario, @idEmpresa, @tokenHash, @fechaCreacionUtc, @fechaExpiracionUtc, @usado, @fechaUsoUtc, @identificadorSolicitado, @emailDestino, @proposito);",
                p =>
                {
                    p.AddWithValue("idUsuario", token.IdUsuario);
                    p.AddWithValue("idEmpresa", token.IdEmpresa);
                    p.AddWithValue("tokenHash", token.TokenHash ?? string.Empty);
                    p.AddWithValue("fechaCreacionUtc", token.FechaCreacionUtc);
                    p.AddWithValue("fechaExpiracionUtc", token.FechaExpiracionUtc);
                    p.AddWithValue("usado", token.Usado);
                    p.AddWithValue("fechaUsoUtc", (object)token.FechaUsoUtc ?? DBNull.Value);
                    p.AddWithValue("identificadorSolicitado", token.IdentificadorSolicitado ?? string.Empty);
                    p.AddWithValue("emailDestino", token.EmailDestino ?? string.Empty);
                    p.AddWithValue("proposito", string.IsNullOrWhiteSpace(token.Proposito) ? "reset" : token.Proposito);
                });
        }

        public Entidades.UsuarioPasswordResetToken ObtenerTokenRecuperacion(string tokenHash)
        {
            var list = ReaderSinRLS(@"
                SELECT *
                FROM usuariopasswordresettokens
                WHERE tokenhash = @tokenHash
                ORDER BY id DESC
                LIMIT 1;",
                dr => new Entidades.UsuarioPasswordResetToken
                {
                    Id = Convert.ToInt32(dr["id"]),
                    IdUsuario = Convert.ToInt32(dr["idusuario"]),
                    IdEmpresa = dr["idempresa"] == DBNull.Value ? 0 : Convert.ToInt32(dr["idempresa"]),
                    TokenHash = Convert.ToString(dr["tokenhash"]),
                    FechaCreacionUtc = Convert.ToDateTime(dr["fechacreacionutc"]),
                    FechaExpiracionUtc = Convert.ToDateTime(dr["fechaexpiracionutc"]),
                    Usado = dr["usado"] != DBNull.Value && Convert.ToBoolean(dr["usado"]),
                    FechaUsoUtc = dr["fechausoutc"] == DBNull.Value ? (DateTime?)null : Convert.ToDateTime(dr["fechausoutc"]),
                    IdentificadorSolicitado = GetString(dr, "identificadorsolicitado"),
                    EmailDestino = GetString(dr, "emaildestino"),
                    Proposito = ColumnaExiste(dr, "proposito") && dr["proposito"] != DBNull.Value ? Convert.ToString(dr["proposito"]) : "reset"
                },
                p => p.AddWithValue("tokenHash", tokenHash ?? string.Empty));

            return list.Count > 0 ? list[0] : null;
        }

        public void MarcarTokenRecuperacionComoUsado(int idToken)
        {
            NonQuerySinRLS(
                "UPDATE usuariopasswordresettokens SET usado = true, fechausoutc = now() WHERE id = @idToken;",
                p => p.AddWithValue("idToken", idToken));
        }

        public void InvalidarTokensPendientesUsuario(int idUsuario, string proposito)
        {
            NonQuerySinRLS(@"
                UPDATE usuariopasswordresettokens
                SET usado = true,
                    fechausoutc = COALESCE(fechausoutc, now())
                WHERE idusuario = @idUsuario
                  AND proposito = @proposito
                  AND usado = false
                  AND fechaexpiracionutc >= now();",
                p =>
                {
                    p.AddWithValue("idUsuario", idUsuario);
                    p.AddWithValue("proposito", string.IsNullOrWhiteSpace(proposito) ? "reset" : proposito);
                });
        }

        // loginubicacionlog no tiene idempresa propio (verificado contra el schema real de SQL
        // Server) -- el filtro por tenant en obtenerLoginUbicacionLog es via JOIN a usuarios
        // (que a su vez no tiene RLS, Etapa 13a), igual que el original.
        public void RegistrarLoginUbicacion(Entidades.LoginUbicacionLog log)
        {
            if (log == null) throw new ArgumentNullException(nameof(log));

            DbPg.NonQuery(_connectionString, _idEmpresa, @"
                INSERT INTO loginubicacionlog
                (idusuario, idsucursal, fechahora, latitud, longitud, precisionmetros, distanciametros, permitido, motivo, ip)
                VALUES
                (@idUsuario, @idSucursal, @fechaHora, @latitud, @longitud, @precisionMetros, @distanciaMetros, @permitido, @motivo, @ip);",
                p =>
                {
                    p.AddWithValue("idUsuario", log.IdUsuario);
                    p.AddWithValue("idSucursal", log.IdSucursal);
                    p.AddWithValue("fechaHora", log.FechaHora);
                    p.AddWithValue("latitud", (object)log.Latitud ?? DBNull.Value);
                    p.AddWithValue("longitud", (object)log.Longitud ?? DBNull.Value);
                    p.AddWithValue("precisionMetros", (object)log.PrecisionMetros ?? DBNull.Value);
                    p.AddWithValue("distanciaMetros", (object)log.DistanciaMetros ?? DBNull.Value);
                    p.AddWithValue("permitido", log.Permitido);
                    p.AddWithValue("motivo", log.Motivo ?? string.Empty);
                    p.AddWithValue("ip", log.Ip ?? string.Empty);
                });
        }

        public DataTable obtenerLoginUbicacionLog(int idEmpresa, DateTime desde, DateTime hasta)
        {
            return DbPg.DataTable(_connectionString, _idEmpresa, @"
                SELECT
                    l.idusuario AS ""IdUsuario"",
                    u.nombre AS ""UsuarioNombre"",
                    l.idsucursal AS ""IdSucursal"",
                    s.sucursal AS ""SucursalNombre"",
                    l.fechahora AS ""FechaHora"",
                    l.latitud AS ""Latitud"",
                    l.longitud AS ""Longitud"",
                    l.precisionmetros AS ""PrecisionMetros"",
                    l.distanciametros AS ""DistanciaMetros"",
                    l.permitido AS ""Permitido"",
                    l.motivo AS ""Motivo"",
                    l.ip AS ""Ip""
                FROM loginubicacionlog l
                INNER JOIN usuarios u ON u.id = l.idusuario
                LEFT JOIN sucursal s ON s.idsucursal = l.idsucursal
                WHERE u.idempresa = @idEmpresa
                  AND l.fechahora BETWEEN @desde AND @hasta
                ORDER BY l.fechahora DESC
                LIMIT 500;",
                p =>
                {
                    p.AddWithValue("idEmpresa", idEmpresa);
                    p.AddWithValue("desde", desde);
                    p.AddWithValue("hasta", hasta);
                });
        }
    }
}
